release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn config.asgi:application -c gunicorn.conf.py
worker: celery -A config worker --loglevel=info
beat: celery -A config beat --loglevel=info
