import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../config/app_colors.dart';
import '../../l10n/app_localizations.dart';
import '../../providers/theme_provider.dart';
import '../../providers/language_provider.dart';
import '../../services/api_service.dart';
import '../../widgets/shimmer_loading.dart';

/// System notification types (auto-generated by backend)
const _systemTypes = {'system', 'youth_dialogue', 'credential', 'verification', 'security', 'account'};

class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> with SingleTickerProviderStateMixin {
  final ApiService _apiService = ApiService();
  List<Map<String, dynamic>> _notifications = [];
  bool _isLoading = true;
  String? _error;
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _loadNotifications();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  List<Map<String, dynamic>> get _adminNotifications =>
      _notifications.where((n) => !_isSystemType(n)).toList();

  List<Map<String, dynamic>> get _systemNotifications =>
      _notifications.where((n) => _isSystemType(n)).toList();

  bool _isSystemType(Map<String, dynamic> notification) {
    final type = notification['notification_type'] as String? ?? 'general';
    return _systemTypes.contains(type);
  }

  Future<void> _loadNotifications() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final response = await _apiService.get('notifications/');
      List<Map<String, dynamic>> items;
      if (response is Map && response['results'] != null) {
        items = List<Map<String, dynamic>>.from(response['results']);
      } else if (response is List) {
        items = List<Map<String, dynamic>>.from(response);
      } else {
        items = [];
      }
      setState(() {
        _notifications = items;
        _isLoading = false;
      });
      // Mark all as read on the server so the badge clears when user goes back
      await _markAllAsRead();
    } catch (e) {
      if (kDebugMode) debugPrint('Notifications load error: $e');
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Future<void> _markAllAsRead() async {
    // Optimistic update — clear dots immediately, sync to server in background.
    // If the API call fails the visual state is still correct for this session;
    // the next fetch will bring the server state back.
    setState(() {
      for (final n in _notifications) {
        n['is_read'] = true;
      }
    });
    try {
      await _apiService.markAllNotificationsAsRead();
    } catch (e) {
      if (kDebugMode) debugPrint('Failed to mark all notifications as read: $e');
    }
  }

  Future<void> _markAsRead(int notificationId) async {
    // Optimistic update — remove the dot before the server round-trip.
    setState(() {
      final index = _notifications.indexWhere((n) => n['id'] == notificationId);
      if (index != -1) {
        _notifications[index]['is_read'] = true;
      }
    });
    try {
      await _apiService.post('notifications/$notificationId/mark-as-read/', {});
    } catch (e) {
      if (kDebugMode) debugPrint('Failed to mark notification as read: $e');
    }
  }

  Future<void> _handleNotificationTap(Map<String, dynamic> notification) async {
    final notificationId = notification['id'] as int;
    final actionType = notification['action_type'] as String?;
    final actionValue = notification['action_value'] as String?;

    // Mark as read
    if (notification['is_read'] != true) {
      await _markAsRead(notificationId);
    }

    // Handle action
    if (actionType == null || actionValue == null || actionValue.isEmpty || actionType == 'none') {
      return;
    }

    if (actionType == 'route') {
      if (!mounted) return;
      Navigator.pushNamed(context, actionValue);
    } else if (actionType == 'url') {
      final uri = Uri.parse(actionValue);
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDarkMode = Provider.of<ThemeProvider>(context).isDarkMode;
    final langCode = Provider.of<LanguageProvider>(context).languageCode;
    final loc = AppLocalizations.of(context);
    final isFr = langCode == 'fr';

    final adminUnread = _adminNotifications.where((n) => n['is_read'] != true).length;
    final systemUnread = _systemNotifications.where((n) => n['is_read'] != true).length;

    return Scaffold(
      appBar: AppBar(
        title: Text(loc.translate('notifications')),
        backgroundColor: AppColors.burundiGreen,
        foregroundColor: Colors.white,
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: Colors.white,
          indicatorWeight: 3,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white60,
          labelStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
          unselectedLabelStyle: const TextStyle(fontWeight: FontWeight.w500, fontSize: 14),
          tabs: [
            Tab(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.campaign_rounded, size: 18),
                  const SizedBox(width: 6),
                  Text(isFr ? 'Annonces' : 'Announcements'),
                  if (adminUnread > 0) ...[
                    const SizedBox(width: 6),
                    _unreadBadge(adminUnread),
                  ],
                ],
              ),
            ),
            Tab(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.settings_rounded, size: 18),
                  const SizedBox(width: 6),
                  Text(isFr ? 'Système' : 'System'),
                  if (systemUnread > 0) ...[
                    const SizedBox(width: 6),
                    _unreadBadge(systemUnread),
                  ],
                ],
              ),
            ),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildTabContent(_adminNotifications, isDarkMode, langCode, loc, isSystem: false),
          _buildTabContent(_systemNotifications, isDarkMode, langCode, loc, isSystem: true),
        ],
      ),
    );
  }

  Widget _unreadBadge(int count) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
      ),
      child: Text(
        count > 99 ? '99+' : count.toString(),
        style: const TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.bold,
          color: AppColors.burundiGreen,
        ),
      ),
    );
  }

  Widget _buildTabContent(
    List<Map<String, dynamic>> notifications,
    bool isDarkMode,
    String langCode,
    AppLocalizations? loc, {
    required bool isSystem,
  }) {
    if (_isLoading) {
      return const ShimmerListItemSkeleton();
    }

    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.wifi_off_rounded, size: 64, color: isDarkMode ? Colors.grey[500] : Colors.grey[400]),
              const SizedBox(height: 16),
              Text(
                loc?.translate('error_loading_notifications') ?? 'Could not load notifications',
                style: TextStyle(
                  fontSize: 17,
                  fontWeight: FontWeight.w600,
                  color: isDarkMode ? Colors.white : Colors.black87,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              Text(
                'Check your connection and try again',
                style: TextStyle(
                  fontSize: 14,
                  color: isDarkMode ? Colors.grey[500] : Colors.grey[600],
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              FilledButton.icon(
                onPressed: _loadNotifications,
                icon: const Icon(Icons.refresh, size: 18),
                label: Text(loc?.translate('retry') ?? 'Retry'),
                style: FilledButton.styleFrom(
                  backgroundColor: AppColors.burundiGreen,
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                ),
              ),
            ],
          ),
        ),
      );
    }

    if (notifications.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              isSystem ? Icons.notifications_active_outlined : Icons.campaign_outlined,
              size: 72,
              color: isDarkMode ? Colors.grey[600] : Colors.grey[400],
            ),
            const SizedBox(height: 16),
            Text(
              isSystem
                  ? (langCode == 'fr' ? 'Aucune notification système' : 'No system notifications')
                  : (langCode == 'fr' ? 'Aucune annonce' : 'No announcements yet'),
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w600,
                color: isDarkMode ? Colors.grey[400] : Colors.grey[600],
              ),
            ),
            const SizedBox(height: 8),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 48),
              child: Text(
                isSystem
                    ? (langCode == 'fr'
                        ? 'Les mises à jour de votre compte et vérifications apparaîtront ici'
                        : 'Account updates and verifications will appear here')
                    : (langCode == 'fr'
                        ? 'Les actualités et annonces apparaîtront ici'
                        : 'News and announcements will appear here'),
                style: TextStyle(
                  fontSize: 14,
                  color: isDarkMode ? Colors.grey[600] : Colors.grey[500],
                ),
                textAlign: TextAlign.center,
              ),
            ),
          ],
        ),
      );
    }

    return RefreshIndicator(
      onRefresh: () async {
        HapticFeedback.mediumImpact();
        await _loadNotifications();
      },
      child: ListView.builder(
        padding: const EdgeInsets.symmetric(vertical: 8),
        itemCount: notifications.length,
        itemBuilder: (context, index) {
          final notification = notifications[index];
          return _buildNotificationCard(notification, isDarkMode, langCode);
        },
      ),
    );
  }

  Widget _buildNotificationCard(Map<String, dynamic> notification, bool isDarkMode, String langCode) {
    final isRead = notification['is_read'] == true;
    final title = langCode == 'fr'
        ? (notification['title_fr'] ?? notification['title'] ?? '')
        : (notification['title'] ?? '');
    final message = langCode == 'fr'
        ? (notification['message_fr'] ?? notification['message'] ?? '')
        : (notification['message'] ?? '');
    final notificationType = notification['notification_type'] as String? ?? 'general';
    final imageUrl = notification['image'] as String?;
    final createdAt = notification['created_at'] as String?;

    // Icon based on notification type
    IconData icon;
    Color iconColor;
    switch (notificationType) {
      case 'article':
        icon = Icons.article;
        iconColor = AppColors.burundiGreen;
        break;
      case 'magazine':
        icon = Icons.auto_stories;
        iconColor = AppColors.auGold;
        break;
      case 'event':
        icon = Icons.event;
        iconColor = AppColors.burundiRed;
        break;
      case 'system':
        icon = Icons.info_rounded;
        iconColor = AppColors.burundiGreen;
        break;
      case 'youth_dialogue':
        icon = Icons.groups_rounded;
        iconColor = Colors.purple;
        break;
      case 'credential':
        icon = Icons.badge_rounded;
        iconColor = Colors.purple;
        break;
      case 'verification':
        icon = Icons.verified_rounded;
        iconColor = Colors.blue;
        break;
      case 'security':
        icon = Icons.security_rounded;
        iconColor = Colors.orange;
        break;
      case 'account':
        icon = Icons.person_rounded;
        iconColor = Colors.teal;
        break;
      default:
        icon = Icons.notifications;
        iconColor = Colors.grey;
    }

    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      elevation: isRead ? 0 : 2,
      color: isRead
          ? (isDarkMode ? Colors.grey[850] : Colors.grey[100])
          : (isDarkMode ? Colors.grey[800] : Colors.white),
      child: InkWell(
        onTap: () => _handleNotificationTap(notification),
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Icon
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: iconColor.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, color: iconColor, size: 24),
              ),
              const SizedBox(width: 12),

              // Content
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(
                            title,
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: isRead ? FontWeight.normal : FontWeight.bold,
                              color: isDarkMode ? Colors.white : Colors.black87,
                            ),
                          ),
                        ),
                        if (!isRead)
                          Container(
                            width: 8,
                            height: 8,
                            decoration: BoxDecoration(
                              color: AppColors.burundiGreen,
                              shape: BoxShape.circle,
                            ),
                          ),
                      ],
                    ),
                    const SizedBox(height: 4),
                    Text(
                      message,
                      style: TextStyle(
                        fontSize: 14,
                        color: isDarkMode ? Colors.grey[400] : Colors.grey[700],
                      ),
                      maxLines: 3,
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (imageUrl != null && imageUrl.isNotEmpty) ...[
                      const SizedBox(height: 8),
                      ClipRRect(
                        borderRadius: BorderRadius.circular(8),
                        child: ConstrainedBox(
                          constraints: const BoxConstraints(maxHeight: 160),
                          child: CachedNetworkImage(
                            imageUrl: imageUrl,
                            width: double.infinity,
                            fit: BoxFit.cover,
                            placeholder: (context, url) => Container(
                              height: 100,
                              color: isDarkMode ? Colors.grey[700] : Colors.grey[200],
                              child: const Center(child: CircularProgressIndicator(strokeWidth: 2)),
                            ),
                            errorWidget: (context, url, error) => const SizedBox.shrink(),
                          ),
                        ),
                      ),
                    ],
                    if (createdAt != null) ...[
                      const SizedBox(height: 8),
                      Text(
                        _formatDateTime(createdAt),
                        style: TextStyle(
                          fontSize: 12,
                          color: isDarkMode ? Colors.grey[600] : Colors.grey[500],
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _formatDateTime(String isoString) {
    try {
      final dateTime = DateTime.parse(isoString);
      final now = DateTime.now();
      final difference = now.difference(dateTime);

      if (difference.inDays == 0) {
        if (difference.inHours == 0) {
          if (difference.inMinutes == 0) {
            return 'Just now';
          }
          return '${difference.inMinutes}m ago';
        }
        return '${difference.inHours}h ago';
      } else if (difference.inDays == 1) {
        return 'Yesterday';
      } else if (difference.inDays < 7) {
        return '${difference.inDays}d ago';
      } else {
        return '${dateTime.day}/${dateTime.month}/${dateTime.year}';
      }
    } catch (e) {
      return '';
    }
  }
}
