import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import '../../config/app_ds.dart';
import '../../widgets/ds/ds_widgets.dart';
import '../../l10n/app_localizations.dart';
import '../../providers/language_provider.dart';
import '../../services/api_service.dart';
import '../../services/deep_link_router.dart';
import '../../widgets/shimmer_loading.dart';
import '../../widgets/app_network_image.dart';

/// System notification types (auto-generated by backend)
const _systemTypes = {'system', 'youth_dialogue', 'credential', 'verification', 'security', 'account'};

class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> with SingleTickerProviderStateMixin {
  final ApiService _apiService = ApiService();
  List<Map<String, dynamic>> _notifications = [];
  bool _isLoading = true;
  String? _error;
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    // Keep the pill filters in sync when the user swipes between tabs.
    _tabController.addListener(() {
      if (mounted) setState(() {});
    });
    _loadNotifications();
  }

  @override
  void dispose() {
    _tabController.dispose();
    // Unread dots stay visible while the screen is open; sync read state on exit.
    if (_notifications.any((n) => n['is_read'] != true)) {
      _apiService.markAllNotificationsAsRead().catchError((e) {
        if (kDebugMode) debugPrint('Failed to mark all notifications as read: $e');
      });
    }
    super.dispose();
  }

  List<Map<String, dynamic>> get _adminNotifications =>
      _notifications.where((n) => !_isSystemType(n)).toList();

  List<Map<String, dynamic>> get _systemNotifications =>
      _notifications.where((n) => _isSystemType(n)).toList();

  bool _isSystemType(Map<String, dynamic> notification) {
    // Use explicit source field from backend; fall back to type-based check
    // for backward compatibility with older API responses
    if (notification.containsKey('source')) {
      return notification['source'] == 'system';
    }
    final type = notification['notification_type'] as String? ?? 'general';
    return _systemTypes.contains(type);
  }

  Future<void> _loadNotifications() async {
    if (!mounted) return;
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final response = await _apiService.get('notifications/', auth: true);
      List<Map<String, dynamic>> items;
      if (response is Map && response['results'] != null) {
        items = List<Map<String, dynamic>>.from(response['results']);
      } else if (response is List) {
        items = List<Map<String, dynamic>>.from(response);
      } else {
        items = [];
      }
      if (!mounted) return;
      setState(() {
        _notifications = items;
        _isLoading = false;
      });
    } catch (e) {
      if (kDebugMode) debugPrint('Notifications load error: $e');
      if (!mounted) return;
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Future<void> _markAllAsRead() async {
    // Optimistic update — clear dots immediately, sync to server in background.
    // If the API call fails the visual state is still correct for this session;
    // the next fetch will bring the server state back.
    if (!mounted) return;
    setState(() {
      for (final n in _notifications) {
        n['is_read'] = true;
      }
    });
    try {
      await _apiService.markAllNotificationsAsRead();
    } catch (e) {
      if (kDebugMode) debugPrint('Failed to mark all notifications as read: $e');
    }
  }

  Future<void> _markAsRead(int notificationId) async {
    // Optimistic update — remove the dot before the server round-trip.
    if (!mounted) return;
    setState(() {
      final index = _notifications.indexWhere((n) => n['id'] == notificationId);
      if (index != -1) {
        _notifications[index]['is_read'] = true;
      }
    });
    try {
      await _apiService.post('notifications/$notificationId/mark-as-read/', {}, auth: true);
    } catch (e) {
      if (kDebugMode) debugPrint('Failed to mark notification as read: $e');
    }
  }

  Future<void> _handleNotificationTap(Map<String, dynamic> notification) async {
    final notificationId = notification['id'] as int;
    final actionType = notification['action_type'] as String?;
    final actionValue = notification['action_value'] as String?;

    // Mark as read
    if (notification['is_read'] != true) {
      await _markAsRead(notificationId);
    }

    // Handle action
    if (actionType == null || actionValue == null || actionValue.isEmpty || actionType == 'none') {
      return;
    }

    if (actionType == 'route' || actionType == 'url') {
      // Validates internal routes against the known set and opens external
      // URLs guarded by canLaunchUrl — never pushes an arbitrary route name.
      await DeepLinkRouter().navigate(actionValue);
    }
  }

  @override
  Widget build(BuildContext context) {
    final langCode = Provider.of<LanguageProvider>(context).languageCode;
    final loc = AppLocalizations.of(context);

    final adminUnread = _adminNotifications.where((n) => n['is_read'] != true).length;
    final systemUnread = _systemNotifications.where((n) => n['is_read'] != true).length;
    final totalUnread = adminUnread + systemUnread;

    return Scaffold(
      backgroundColor: Ds.bg(context),
      appBar: AppBar(
        title: Text(loc.translate('notifications')),
        actions: [
          if (totalUnread > 0)
            TextButton(
              onPressed: _markAllAsRead,
              child: Text(
                loc.translate('rs_notif_mark_all_read'),
                style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w700,
                    color: Colors.white.withValues(alpha: 0.85)),
              ),
            ),
          const SizedBox(width: 4),
        ],
      ),
      body: Column(
        children: [
          // The comp uses pill filters rather than an underlined tab bar.
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 4),
            child: Row(
              children: [
                _tabChip(0, loc.translate('rs_notif_announcements'), adminUnread),
                const SizedBox(width: 8),
                _tabChip(1, loc.translate('rs_notif_system'), systemUnread),
              ],
            ),
          ),
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: [
                _buildTabContent(_adminNotifications, langCode, loc,
                    isSystem: false, storageKey: 'notif_admin'),
                _buildTabContent(_systemNotifications, langCode, loc,
                    isSystem: true, storageKey: 'notif_system'),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _tabChip(int index, String label, int unread) {
    final selected = _tabController.index == index;
    return DsFilterChip(
      unread > 0 ? '$label ($unread)' : label,
      selected: selected,
      onTap: () => setState(() => _tabController.animateTo(index)),
    );
  }

  Widget _buildTabContent(
    List<Map<String, dynamic>> notifications,
    String langCode,
    AppLocalizations loc, {
    required bool isSystem,
    String storageKey = 'notif',
  }) {
    if (_isLoading) return const ShimmerListItemSkeleton();

    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.wifi_off_rounded, size: 56, color: Ds.muted(context)),
              const SizedBox(height: 16),
              Text(
                loc.translate('error_loading_notifications'),
                textAlign: TextAlign.center,
                style: TextStyle(
                    fontSize: 16, fontWeight: FontWeight.w700, color: Ds.ink(context)),
              ),
              const SizedBox(height: 8),
              Text(loc.translate('rs_notif_check_connection'),
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 14, color: Ds.body(context))),
              const SizedBox(height: 20),
              DsOutlineButton(loc.translate('retry'),
                  radius: Ds.rPill, onTap: _loadNotifications),
            ],
          ),
        ),
      );
    }

    if (notifications.isEmpty) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 40),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                isSystem
                    ? Icons.notifications_active_outlined
                    : Icons.campaign_outlined,
                size: 64,
                color: Ds.muted(context),
              ),
              const SizedBox(height: 16),
              Text(
                loc.translate(isSystem
                    ? 'rs_notif_no_system'
                    : 'rs_notif_no_announcements'),
                style: TextStyle(
                    fontSize: 17, fontWeight: FontWeight.w700, color: Ds.ink(context)),
              ),
              const SizedBox(height: 8),
              Text(
                loc.translate(isSystem
                    ? 'rs_notif_system_hint'
                    : 'rs_notif_announcements_hint'),
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 14, color: Ds.body(context)),
              ),
            ],
          ),
        ),
      );
    }

    // Split into Today / Earlier the way the comp groups the inbox.
    final today = <Map<String, dynamic>>[];
    final earlier = <Map<String, dynamic>>[];
    final now = DateTime.now();
    for (final n in notifications) {
      final created = DateTime.tryParse(n['created_at']?.toString() ?? '');
      final isToday = created != null &&
          created.year == now.year &&
          created.month == now.month &&
          created.day == now.day;
      (isToday ? today : earlier).add(n);
    }

    return RefreshIndicator(
      color: Ds.green,
      onRefresh: () async {
        HapticFeedback.mediumImpact();
        await _loadNotifications();
      },
      child: ListView(
        key: PageStorageKey<String>(storageKey),
        padding: const EdgeInsets.only(top: 8, bottom: 32),
        children: [
          if (today.isNotEmpty) ...[
            DsGroupLabel(loc.translate('rs_today'),
                padding: const EdgeInsets.fromLTRB(22, 8, 22, 8)),
            DsTileGroup(
              children: [for (final n in today) _buildNotificationRow(n, langCode)],
            ),
          ],
          if (earlier.isNotEmpty) ...[
            DsGroupLabel(loc.translate('rs_earlier'),
                padding: const EdgeInsets.fromLTRB(22, 8, 22, 8)),
            DsTileGroup(
              children: [for (final n in earlier) _buildNotificationRow(n, langCode)],
            ),
          ],
        ],
      ),
    );
  }

  /// Tint + icon for each notification type, using the redesign palette.
  (IconData, Color, Color) _typeStyle(String type) {
    switch (type) {
      case 'article':
        return (Icons.newspaper_rounded, Ds.greenTint, Ds.green);
      case 'magazine':
        return (Icons.auto_stories_rounded, Ds.greenTint, Ds.green);
      case 'event':
        return (Icons.event_rounded, Ds.goldTint, Ds.goldDeep);
      case 'live_feed':
        return (Icons.live_tv_rounded, Ds.redTint, Ds.red);
      case 'youth_dialogue':
        return (Icons.groups_rounded, Ds.greenTint, Ds.green);
      case 'credential':
        return (Icons.badge_rounded, Ds.greenTint, Ds.green);
      case 'verification':
        return (Icons.verified_rounded, Ds.blueTint, Ds.blue);
      case 'security':
        return (Icons.security_rounded, Ds.goldTint, Ds.goldDeep);
      case 'account':
        return (Icons.person_rounded, Ds.greenTint, Ds.green);
      default:
        return (Icons.notifications_rounded, Ds.greenTint, Ds.green);
    }
  }

  Widget _buildNotificationRow(Map<String, dynamic> notification, String langCode) {
    final isRead = notification['is_read'] == true;
    final title = langCode == 'fr'
        ? (notification['title_fr'] ?? notification['title'] ?? '')
        : (notification['title'] ?? '');
    final message = langCode == 'fr'
        ? (notification['message_fr'] ?? notification['message'] ?? '')
        : (notification['message'] ?? '');
    final type = notification['notification_type'] as String? ?? 'general';
    final imageUrl = notification['image'] as String?;
    final createdAt = notification['created_at'] as String?;
    final (icon, tint, color) = _typeStyle(type);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return InkWell(
      onTap: () => _handleNotificationTap(notification),
      child: Container(
        // Unread rows sit on a faint green wash in the comp.
        color: isRead
            ? Colors.transparent
            : (isDark ? Ds.green.withValues(alpha: 0.08) : const Color(0xFFF4FAF4)),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            DsIconSquare(icon,
                tint: isDark ? color.withValues(alpha: 0.18) : tint, color: color),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: isRead ? FontWeight.w600 : FontWeight.w700,
                      color: Ds.ink(context),
                    ),
                  ),
                  if (message.toString().isNotEmpty) ...[
                    const SizedBox(height: 2),
                    Text(
                      message,
                      maxLines: 3,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                          fontSize: 12,
                          height: 1.35,
                          color: isRead ? Ds.muted(context) : Ds.body(context)),
                    ),
                  ],
                  if (imageUrl != null && imageUrl.isNotEmpty) ...[
                    const SizedBox(height: 8),
                    ClipRRect(
                      borderRadius: BorderRadius.circular(Ds.rTile),
                      child: ConstrainedBox(
                        constraints: const BoxConstraints(maxHeight: 160),
                        child: AppNetworkImage(
                          imageUrl: imageUrl,
                          width: double.infinity,
                          fit: BoxFit.cover,
                          placeholder: (context, url) =>
                              const DsImagePlaceholder(height: 100),
                          errorWidget: (context, url, error) => const SizedBox.shrink(),
                        ),
                      ),
                    ),
                  ],
                  if (createdAt != null) ...[
                    const SizedBox(height: 4),
                    Text(_formatDateTime(createdAt), style: Ds.meta(context)),
                  ],
                ],
              ),
            ),
            if (!isRead)
              Container(
                margin: const EdgeInsets.only(left: 10, top: 6),
                width: 8,
                height: 8,
                decoration:
                    const BoxDecoration(color: Ds.green, shape: BoxShape.circle),
              ),
          ],
        ),
      ),
    );
  }

  String _formatDateTime(String isoString) {
    try {
      final dateTime = DateTime.parse(isoString);
      final now = DateTime.now();
      final difference = now.difference(dateTime);

      if (difference.inDays == 0) {
        if (difference.inHours == 0) {
          if (difference.inMinutes == 0) {
            return 'Just now';
          }
          return '${difference.inMinutes}m ago';
        }
        return '${difference.inHours}h ago';
      } else if (difference.inDays == 1) {
        return 'Yesterday';
      } else if (difference.inDays < 7) {
        return '${difference.inDays}d ago';
      } else {
        return '${dateTime.day}/${dateTime.month}/${dateTime.year}';
      }
    } catch (e) {
      return '';
    }
  }
}
