# Generated by Django 4.2.28 on 2026-02-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summit_year', models.CharField(default='2026', max_length=10)),
                ('summit_theme', models.CharField(max_length=300)),
                ('summit_theme_fr', models.CharField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_fr', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('content_fr', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('economy', 'Economy'), ('culture', 'Culture'), ('diplomacy', 'Diplomacy')], max_length=20)),
                ('publish_date', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='EmbassyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('embassy', 'Embassy'), ('consulate', 'Consulate'), ('event_venue', 'Event Venue'), ('office', 'Office')], default='embassy', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='embassies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Embassy Locations',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('embassy', 'Embassy'), ('police', 'Police'), ('ambulance', 'Ambulance'), ('fire', 'Fire Department')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('label', models.CharField(max_length=100)),
                ('label_fr', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LiveFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('stream_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='live_feeds/')),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('recorded', 'Recorded')], default='upcoming', max_length=20)),
                ('viewer_count', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, help_text='e.g. 1h 30m', max_length=50)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagazineEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='magazines/')),
                ('pdf_file', models.FileField(blank=True, upload_to='magazines/pdfs/')),
                ('publish_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('official_documents', 'Official Documents'), ('country_info', 'Country Information'), ('media', 'Media Resources'), ('reference', 'Reference Guides')], max_length=30)),
                ('file', models.FileField(upload_to='resources/')),
                ('file_size', models.CharField(help_text='e.g. 2.4 MB', max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('zip', 'ZIP')], default='pdf', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
