# Generated by Django 4.2.28 on 2026-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='feature_cards/')),
                ('gradient_start', models.CharField(default='#1EB53A', help_text='Hex color e.g. #1EB53A', max_length=10)),
                ('gradient_end', models.CharField(default='#4CAF50', help_text='Hex color e.g. #4CAF50', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
