# Generated by Django 4.2.28 on 2026-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_fcm_token_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('overview', models.TextField()),
                ('overview_fr', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list, help_text='List of key objectives')),
                ('objectives_fr', models.JSONField(blank=True, default=list)),
                ('impact_areas', models.JSONField(default=list, help_text='List of impact area objects with icon, title, description')),
                ('impact_areas_fr', models.JSONField(blank=True, default=list)),
                ('current_initiatives', models.TextField(blank=True)),
                ('current_initiatives_fr', models.TextField(blank=True)),
                ('icon_name', models.CharField(help_text='Material icon name', max_length=50)),
                ('gradient_colors', models.JSONField(default=list, help_text='List of 2 hex colors for gradient')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='agendas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Priority Agenda',
                'verbose_name_plural': 'Priority Agendas',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
