# Generated by Django 4.2.28 on 2026-02-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_priorityagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='gallery/covers/')),
                ('photo_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('display_name_fr', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('handle', models.CharField(help_text='e.g. @BurundiAU2026', max_length=100)),
                ('follower_count', models.CharField(blank=True, help_text='e.g. 45K', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('icon_color', models.CharField(default='#1EB53A', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='YouTube or other video URL')),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/')),
                ('duration', models.CharField(help_text='e.g. 5:30', max_length=20)),
                ('category', models.CharField(choices=[('highlight', 'Highlights'), ('speech', 'Speeches'), ('documentary', 'Documentary'), ('interview', 'Interview'), ('event', 'Event Coverage'), ('cultural', 'Cultural')], default='highlight', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('publish_date', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-is_featured', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_fr', models.CharField(blank=True, max_length=300)),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
