# Generated by Django 4.2.28 on 2026-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_galleryalbum_socialmedialink_video_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityagenda',
            name='plain_color',
            field=models.CharField(default='#1EB53A', help_text='Plain color (hex) - used when gradient is disabled', max_length=10),
        ),
        migrations.AddField(
            model_name='priorityagenda',
            name='use_gradient',
            field=models.BooleanField(default=False, help_text='Use gradient instead of plain color'),
        ),
        migrations.AlterField(
            model_name='priorityagenda',
            name='gradient_colors',
            field=models.JSONField(blank=True, default=list, help_text='List of 2 hex colors for gradient - used when gradient is enabled'),
        ),
    ]
