# Generated by Django 4.2.28 on 2026-02-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_priorityagenda_plain_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityagenda',
            name='gradient_colors',
        ),
        migrations.RemoveField(
            model_name='priorityagenda',
            name='plain_color',
        ),
        migrations.RemoveField(
            model_name='priorityagenda',
            name='use_gradient',
        ),
        migrations.AlterField(
            model_name='priorityagenda',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main image for this agenda', null=True, upload_to='agendas/'),
        ),
    ]
