# Generated by Django 4.2.28 on 2026-02-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_priorityagenda_gradient_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineedition',
            name='external_url',
            field=models.URLField(blank=True, help_text='External link to PDF (used if no file uploaded)'),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g. 2.4 MB', max_length=20),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages in the PDF'),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='magazineedition',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file', upload_to='magazines/pdfs/'),
        ),
    ]
