# Generated by Django 4.2.28 on 2026-02-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_magazineedition_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='magazines/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_fr', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.magazineedition')),
            ],
            options={
                'verbose_name': 'Magazine Image',
                'verbose_name_plural': 'Magazine Images',
                'ordering': ['order'],
            },
        ),
    ]
