# Generated by Django 4.2.28 on 2026-02-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_magazine_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.magazineedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'edition')},
            },
        ),
    ]
