# Generated by Django 4.2.28 on 2026-02-28 12:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_magazine_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='article_media/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='embassylocation',
            name='image',
            field=models.ImageField(blank=True, upload_to='embassies/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='image',
            field=models.ImageField(blank=True, upload_to='feature_cards/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(upload_to='gallery/covers/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery/photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero_slides/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='livefeed',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='live_feeds/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='magazineedition',
            name='cover_image',
            field=models.ImageField(upload_to='magazines/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='magazineedition',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file', upload_to='magazines/pdfs/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='magazineimage',
            name='image',
            field=models.ImageField(upload_to='magazines/gallery/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='priorityagenda',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main image for this agenda', null=True, upload_to='agendas/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=255, validators=[core.validators.validate_fcm_token]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='videos/thumbnails/', validators=[core.validators.validate_image_file]),
        ),
    ]
