# Generated by Django 4.2.28 on 2026-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_article_image_alter_articlemedia_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('url', 'External URL'), ('route', 'App Route')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='action_value',
            field=models.CharField(blank=True, help_text='URL for "url" type, route name for "route" type (e.g. "/news", "/magazine")', max_length=500),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Flutter IconData name, e.g. "stars", "travel_explore"', max_length=50),
        ),
    ]
