# Generated by Django 4.2.28 on 2026-02-28 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_feature_card_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('title_fr', models.CharField(blank=True, help_text='French title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('message_fr', models.TextField(blank=True, help_text='French message')),
                ('notification_type', models.CharField(choices=[('general', 'General Announcement'), ('article', 'New Article'), ('magazine', 'New Magazine'), ('event', 'Event Reminder'), ('system', 'System Update')], default='general', max_length=20)),
                ('action_type', models.CharField(choices=[('none', 'No Action'), ('url', 'External URL'), ('route', 'App Route')], default='none', help_text='What happens when user taps notification', max_length=10)),
                ('action_value', models.CharField(blank=True, help_text='URL or route name (e.g., /news, /magazine)', max_length=500)),
                ('is_global', models.BooleanField(default=True, help_text='Send to all users (uncheck to send to specific users)')),
                ('is_active', models.BooleanField(default=True, help_text='Active notifications appear in app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text='Specific users (only if not global)', related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
