# Generated by Django 4.2.28 on 2026-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('badge', 'Badge Text'), ('title_line1', 'Title Line 1'), ('title_line2', 'Title Line 2'), ('year', 'Year')], max_length=50, unique=True)),
                ('text_en', models.CharField(max_length=200)),
                ('text_fr', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Text Content',
                'verbose_name_plural': 'Hero Text Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fr', models.CharField(blank=True, max_length=100)),
                ('icon_name', models.CharField(help_text='Flutter icon name (e.g. live_tv, menu_book, article)', max_length=50)),
                ('action_type', models.CharField(choices=[('route', 'App Route'), ('url', 'External URL')], max_length=10)),
                ('action_value', models.CharField(help_text='Route name (e.g. /live-feeds) or URL', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_live_indicator', models.BooleanField(default=False, help_text='Show red "LIVE" badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Access Menu Item',
                'verbose_name_plural': 'Quick Access Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
