# Generated by Django 4.2.28 on 2026-03-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hero_text_and_menu_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
