# Generated by Django 4.2.28 on 2026-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='extra_content',
            field=models.TextField(blank=True, help_text='Additional text section for the detail page'),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='extra_content_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='impact_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of {icon, title, description} objects'),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='impact_areas_fr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet point strings'),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='key_points_fr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='overview',
            field=models.TextField(blank=True, help_text='Extended description for the detail page'),
        ),
        migrations.AddField(
            model_name='featurecard',
            name='overview_fr',
            field=models.TextField(blank=True),
        ),
    ]
