# Generated by Django 4.2.28 on 2026-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_featurecard_extra_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecard',
            name='icon_name',
            field=models.CharField(blank=True, choices=[('stars', 'Stars'), ('travel_explore', 'Travel / Explore'), ('public', 'Globe / Public'), ('security', 'Security / Shield'), ('groups', 'Groups / People'), ('gavel', 'Gavel / Justice'), ('handshake', 'Handshake'), ('trending_up', 'Trending Up / Growth'), ('auto_stories', 'Book / Stories'), ('campaign', 'Campaign / Megaphone'), ('flag', 'Flag'), ('workspace_premium', 'Premium / Award'), ('landscape', 'Landscape / Nature'), ('music_note', 'Music Note'), ('restaurant', 'Restaurant / Food'), ('diversity_3', 'Diversity / Community'), ('water_drop', 'Water Drop'), ('health_and_safety', 'Health & Safety'), ('school', 'School / Education'), ('agriculture', 'Agriculture'), ('business', 'Business / Trade'), ('computer', 'Computer / Digital'), ('factory', 'Factory / Industry'), ('local_shipping', 'Shipping / Transport')], help_text='Icon displayed on the card', max_length=50),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='impact_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of impact areas. Each item: {"icon": "icon_name", "title": "Title", "description": "Description"}. Available icons: stars, public, security, groups, trending_up, landscape, music_note, restaurant, diversity_3, health_and_safety, school, agriculture, business, computer, factory, local_shipping'),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet point strings, e.g. ["Point one", "Point two"]'),
        ),
    ]
