# Generated by Django 4.2.28 on 2026-03-17 19:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_featurecard_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a custom icon image (PNG/SVG recommended). Overrides icon_name.', upload_to='feature_cards/icons/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='icon_name',
            field=models.CharField(blank=True, choices=[('stars', 'Stars'), ('travel_explore', 'Travel / Explore'), ('public', 'Globe / Public'), ('security', 'Security / Shield'), ('groups', 'Groups / People'), ('gavel', 'Gavel / Justice'), ('handshake', 'Handshake'), ('trending_up', 'Trending Up / Growth'), ('auto_stories', 'Book / Stories'), ('campaign', 'Campaign / Megaphone'), ('flag', 'Flag'), ('workspace_premium', 'Premium / Award'), ('landscape', 'Landscape / Nature'), ('music_note', 'Music Note'), ('restaurant', 'Restaurant / Food'), ('diversity_3', 'Diversity / Community'), ('water_drop', 'Water Drop'), ('health_and_safety', 'Health & Safety'), ('school', 'School / Education'), ('agriculture', 'Agriculture'), ('business', 'Business / Trade'), ('computer', 'Computer / Digital'), ('factory', 'Factory / Industry'), ('local_shipping', 'Shipping / Transport')], help_text='Fallback icon if no image is uploaded', max_length=50),
        ),
    ]
