# Generated by Django 4.2.28 on 2026-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_featurecard_icon_image_alter_featurecard_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickaccessmenuitem',
            name='badge_color',
            field=models.CharField(blank=True, default='#E53935', help_text='Badge background color (hex). Default: red', max_length=10),
        ),
        migrations.AddField(
            model_name='quickaccessmenuitem',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Promo badge text e.g. "NEW", "HOT". Leave blank for no badge.', max_length=10),
        ),
    ]
