# Generated by Django 4.2.28 on 2026-03-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_quickaccessmenuitem_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickaccessmenuitem',
            name='auto_badge',
            field=models.BooleanField(default=True, help_text='Automatically show "NEW" badge when fresh content exists for this route'),
        ),
        migrations.AddField(
            model_name='quickaccessmenuitem',
            name='auto_badge_days',
            field=models.IntegerField(default=3, help_text='Number of days content is considered "new"'),
        ),
        migrations.AlterField(
            model_name='quickaccessmenuitem',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Manual badge text e.g. "HOT", "PROMO". Overrides auto badge if set.', max_length=10),
        ),
    ]
