# Generated by Django 4.2.28 on 2026-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_quickaccessmenuitem_auto_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='User has verified badge (approved by admin)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, help_text='When user requested verification', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved verification', null=True),
        ),
    ]
