# Generated by Django 4.2.28 on 2026-03-18 13:44

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold Badge'), ('BLUE', 'Blue Badge')], help_text='Type of verification badge (Gold for VIPs, Blue for regular verified users)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('he', 'H.E. (His/Her Excellency)'), ('amb', 'Ambassador'), ('hon', 'Honorable'), ('other', 'Other')], help_text='Title/Role (Mr, Mrs, H.E, etc.)', max_length=10)),
                ('full_name', models.CharField(help_text='Full legal name', max_length=200)),
                ('email', models.EmailField(help_text='Professional email (no gmail/yahoo/outlook)', max_length=254, validators=[core.validators.validate_professional_email])),
                ('phone_number', models.CharField(help_text='Phone number for SMS verification', max_length=20)),
                ('phone_verified', models.BooleanField(default=False, help_text='Phone number verified via Twilio SMS')),
                ('position_role', models.CharField(help_text='Current position/role', max_length=200)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL (optional)')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL (optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('appealed', 'Appealed')], default='pending', max_length=20)),
                ('badge_type', models.CharField(blank=True, choices=[('GOLD', 'Gold Badge'), ('BLUE', 'Blue Badge')], help_text='Badge type assigned by admin (Gold or Blue)', max_length=10, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Admin-written reason for rejection (shown to user)')),
                ('appeal_message', models.TextField(blank=True, help_text='User appeal message if rejected')),
                ('appeal_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
