# Generated by Django 4.2.28 on 2026-03-18 18:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userprofile_badge_type_verificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name e.g. Bujumbura', max_length=100)),
                ('latitude', models.FloatField(help_text='City latitude for weather API')),
                ('longitude', models.FloatField(help_text='City longitude for weather API')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for this city (blurred in app)', null=True, upload_to='weather/backgrounds/', validators=[core.validators.validate_image_file])),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default cities cannot be removed by users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather City',
                'verbose_name_plural': 'Weather Cities',
                'ordering': ['order', 'name'],
            },
        ),
    ]
