# Generated by Django 4.2.28 on 2026-03-18 19:10

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_weathercity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('event', 'Event Registration'), ('greeting', 'Greeting/Holiday Wish'), ('announcement', 'General Announcement'), ('survey', 'Survey/Feedback')], default='event', max_length=20)),
                ('event_title', models.CharField(blank=True, max_length=300)),
                ('event_title_fr', models.CharField(blank=True, max_length=300)),
                ('event_description', models.TextField(blank=True)),
                ('event_description_fr', models.TextField(blank=True)),
                ('event_poster', models.ImageField(blank=True, upload_to='event_posters/', validators=[core.validators.validate_image_file])),
                ('is_registration_enabled', models.BooleanField(default=True, help_text='Enable/disable registration form')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_registrations', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('send_confirmation_email', models.BooleanField(default=True)),
                ('confirmation_message', models.TextField(blank=True, help_text='Message sent to user after registration')),
                ('confirmation_message_fr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='core.featurecard')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='push_recipient_count',
            field=models.IntegerField(default=0, help_text='Number of users who received push'),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False, help_text='Has push notification been sent?'),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_age_max',
            field=models.IntegerField(blank=True, help_text='Maximum age (leave blank for no limit)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_age_min',
            field=models.IntegerField(blank=True, help_text='Minimum age (leave blank for no limit)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Filter by gender (leave blank for all)', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_nationality',
            field=models.CharField(blank=True, help_text='Filter by nationality (leave blank for all)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age-based targeting', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, help_text='User nationality/country', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Send to all users (uncheck to use filters below)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users (optional, overrides filters)', related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('email', 'Email'), ('phone', 'Phone Number'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('file', 'File Upload'), ('image', 'Image Upload'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('nationality', 'Nationality'), ('passport', 'Passport Number')], max_length=20)),
                ('field_label', models.CharField(help_text='Label shown to user', max_length=200)),
                ('field_label_fr', models.CharField(blank=True, max_length=200)),
                ('field_name', models.CharField(help_text='Internal field name (e.g., "full_name", "passport_number")', max_length=100)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('placeholder_fr', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this field')),
                ('options', models.JSONField(blank=True, default=list, help_text='For select/checkbox fields: ["Option 1", "Option 2"]')),
                ('validation_regex', models.CharField(blank=True, help_text='Optional regex for validation', max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('help_text_fr', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.eventregistration')),
            ],
            options={
                'verbose_name': 'Registration Form Field',
                'verbose_name_plural': 'Registration Form Fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict, help_text='All form field values')),
                ('uploaded_files', models.JSONField(blank=True, default=list, help_text='List of uploaded file URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.eventregistration')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Submission',
                'verbose_name_plural': 'Event Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('event_registration', 'user')},
            },
        ),
    ]
