# Generated by Django 4.2.28 on 2026-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_eventregistration_notification_push_recipient_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When off, event is hidden from the app'),
        ),
    ]
