# Generated by Django 4.2.28 on 2026-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, MOV, etc.) or leave empty if using URL', upload_to='videos/files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or external video URL (leave empty if uploading file)'),
        ),
    ]
