# Generated by Django 4.2.28 on 2026-03-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_video_video_file_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='country_code',
            field=models.CharField(default='+1', help_text='Country calling code (e.g. +1, +257)', max_length=10),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verified via OTP'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='first_name',
            field=models.CharField(default='', help_text='First name (for identity verification)', max_length=100),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='last_name',
            field=models.CharField(default='', help_text='Last name (for identity verification)', max_length=100),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='reasoning_message',
            field=models.TextField(blank=True, help_text='User explanation for why they deserve the verification badge'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('contact', models.CharField(help_text='Email or phone number', max_length=200)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
