# Generated by Django 4.2.28 on 2026-03-23 17:51

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_verificationrequest_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecard',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('url', 'External URL'), ('route', 'App Route')], default='none', help_text='Leave as "No Action" to open detail page. Use URL/Route only for special redirects.', max_length=10),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='action_value',
            field=models.CharField(blank=True, help_text='Only needed for URL or Route overrides. Leave blank for normal cards.', max_length=500),
        ),
        migrations.CreateModel(
            name='FeatureCardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='feature_card_media/', validators=[core.validators.validate_image_file])),
                ('video_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_fr', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.featurecard')),
            ],
            options={
                'verbose_name': 'Feature Card Media',
                'verbose_name_plural': 'Feature Card Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCardKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('text_fr', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('feature_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_point_items', to='core.featurecard')),
            ],
            options={
                'verbose_name': 'Key Point',
                'verbose_name_plural': 'Key Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCardImpactArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(choices=[('stars', 'Stars'), ('travel_explore', 'Travel / Explore'), ('public', 'Globe / Public'), ('security', 'Security / Shield'), ('groups', 'Groups / People'), ('gavel', 'Gavel / Justice'), ('handshake', 'Handshake'), ('trending_up', 'Trending Up / Growth'), ('auto_stories', 'Book / Stories'), ('campaign', 'Campaign / Megaphone'), ('flag', 'Flag'), ('workspace_premium', 'Premium / Award'), ('landscape', 'Landscape / Nature'), ('music_note', 'Music Note'), ('restaurant', 'Restaurant / Food'), ('diversity_3', 'Diversity / Community'), ('water_drop', 'Water Drop'), ('health_and_safety', 'Health & Safety'), ('school', 'School / Education'), ('agriculture', 'Agriculture'), ('business', 'Business / Trade'), ('computer', 'Computer / Digital'), ('factory', 'Factory / Industry'), ('local_shipping', 'Shipping / Transport')], default='stars', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('feature_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_area_items', to='core.featurecard')),
            ],
            options={
                'verbose_name': 'Impact Area',
                'verbose_name_plural': 'Impact Areas',
                'ordering': ['order'],
            },
        ),
    ]
