# Generated by Django 4.2.28 on 2026-03-23 17:51

from django.db import migrations


def migrate_json_to_models(apps, schema_editor):
    """Copy JSON key_points and impact_areas into the new child models."""
    FeatureCard = apps.get_model('core', 'FeatureCard')
    KeyPoint = apps.get_model('core', 'FeatureCardKeyPoint')
    ImpactArea = apps.get_model('core', 'FeatureCardImpactArea')

    for card in FeatureCard.objects.all():
        # Migrate key_points
        kp_en = card.key_points or []
        kp_fr = card.key_points_fr or []
        for i, text in enumerate(kp_en):
            KeyPoint.objects.create(
                feature_card=card,
                text=str(text),
                text_fr=str(kp_fr[i]) if i < len(kp_fr) else '',
                order=i,
            )

        # Migrate impact_areas
        ia_en = card.impact_areas or []
        ia_fr = card.impact_areas_fr or []
        for i, area in enumerate(ia_en):
            if not isinstance(area, dict):
                continue
            fr_area = ia_fr[i] if i < len(ia_fr) and isinstance(ia_fr[i], dict) else {}
            ImpactArea.objects.create(
                feature_card=card,
                icon_name=area.get('icon', 'stars'),
                title=area.get('title', ''),
                title_fr=fr_area.get('title', ''),
                description=area.get('description', ''),
                description_fr=fr_area.get('description', ''),
                order=i,
            )


def reverse_migration(apps, schema_editor):
    """No-op reverse — JSON fields still contain original data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_feature_card_child_models'),
    ]

    operations = [
        migrations.RunPython(migrate_json_to_models, reverse_migration),
    ]
