# Generated by Django 4.2.28 on 2026-03-23 18:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_migrate_feature_card_json_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecardmedia',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no file uploaded)'),
        ),
        migrations.AddField(
            model_name='featurecardmedia',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, MOV, etc.), OR paste a URL below', upload_to='feature_card_media/videos/'),
        ),
        migrations.AlterField(
            model_name='featurecardmedia',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file, OR paste a URL below', upload_to='feature_card_media/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='featurecardmedia',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/external video URL (used if no file uploaded)'),
        ),
    ]
