# Generated by Django 4.2.28 on 2026-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_media_image_url_and_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterUniqueTogether(
            name='eventsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='feature_card',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='allow_proxy_registration',
            field=models.BooleanField(default=False, help_text='Allow users to register on behalf of others'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for "Contact Us" button', max_length=254),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone for "Contact Us" button', max_length=50),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Event start date/time (for countdown)', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='Event end date/time (multi-day events)', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide in app'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue name', max_length=300),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='venue_address',
            field=models.CharField(blank=True, help_text='Full address for directions', max_length=500),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='venue_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='is_proxy',
            field=models.BooleanField(default=False, help_text='Submitted on behalf of someone else'),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='proxy_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='proxy_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='proxy_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event_title',
            field=models.CharField(max_length=300),
        ),
    ]
