# Generated by Django 4.2.28 on 2026-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_make_event_registration_standalone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('email', 'Email'), ('phone', 'Phone Number'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('file', 'File Upload'), ('image', 'Image Upload'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Single Checkbox'), ('multi_checkbox', 'Multiple Checkboxes'), ('country', 'Country Selector'), ('nationality', 'Nationality'), ('passport', 'Passport Number'), ('url', 'URL / Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For select/radio/multi_checkbox: ["Option 1", "Option 2"]'),
        ),
    ]
