# Generated by Django 4.2.28 on 2026-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_radio_multi_checkbox_field_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
    ]
