# Generated by Django 4.2.28 on 2026-03-25 10:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auditlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image shown in push notification and in-app list', null=True, upload_to='notifications/', validators=[core.validators.validate_image_file]),
        ),
    ]
