# Generated by Django 4.2.28 on 2026-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_badge_type',
            field=models.CharField(blank=True, choices=[('BLUE', 'Blue Badge'), ('GOLD', 'Gold Badge')], help_text='Filter by badge type (leave blank for any verified)', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_verified_only',
            field=models.BooleanField(default=False, help_text='Only send to verified users (blue or gold badge)'),
        ),
    ]
