# Generated by Django 4.2.28 on 2026-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_nationality_choices_and_multi_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Date when account will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deactivated',
            field=models.BooleanField(default=False, help_text='User chose "Take a Break" - account inactive until they log in again'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_scheduled_for_deletion',
            field=models.BooleanField(default=False, help_text='User requested account deletion - will be purged after 30 days'),
        ),
    ]
