# Generated by Django 4.2.28 on 2026-03-25 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_add_account_deactivation_and_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., Content Editor, Event Manager)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this role is responsible for')),
                ('permissions', models.JSONField(default=list, help_text='List of permission keys this role grants (e.g., ["content", "gallery"])')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'ordering': ['name'],
            },
        ),
    ]
