# Generated by Django 4.2.28 on 2026-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_admin_role_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL (optional)'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL (optional)'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='other_social_url',
            field=models.URLField(blank=True, help_text='Other social media URL (optional)'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL (optional)'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL (optional)'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL (optional)'),
        ),
    ]
