# Generated by Django 4.2.28 on 2026-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='stream_type',
            field=models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube'), ('zoom', 'Zoom')], default='video', help_text='Auto-detected from URL on save. Zoom/YouTube open externally.', max_length=20),
        ),
    ]
