# Generated by Django 4.2.28 on 2026-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_livefeed_stream_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefeed',
            name='stream_type',
            field=models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('webex', 'Webex'), ('meet', 'Google Meet'), ('external', 'External Link')], default='video', help_text='Auto-detected from URL on save. Zoom/YouTube open externally.', max_length=20),
        ),
    ]
