# Generated by Django 4.2.28 on 2026-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_livefeed_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID for Zoom/Teams/Webex (shown to users)', max_length=100),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='passcode',
            field=models.CharField(blank=True, help_text='Meeting passcode (shown to users)', max_length=100),
        ),
        migrations.AlterField(
            model_name='livefeed',
            name='stream_type',
            field=models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('webex', 'Webex'), ('meet', 'Google Meet'), ('external', 'External Link')], default='video', help_text='Auto-detected from URL on save. External platforms open in their app.', max_length=20),
        ),
    ]
