# Generated by Django 4.2.28 on 2026-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_livefeed_meeting_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='sms_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS OTP verification via Twilio'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable WhatsApp OTP verification via Twilio'),
        ),
    ]
