# Generated by Django 4.2.28 on 2026-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_appsettings_verification_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='live_agent_online',
            field=models.BooleanField(default=False, help_text='When ON, users see Live Agent chat option in support'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_live_chat',
            field=models.BooleanField(default=False, help_text='Whether this was a live agent session'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User rating 1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='rating_comment',
            field=models.TextField(blank=True, help_text='Optional feedback from user'),
        ),
    ]
