# Generated by Django 4.2.28 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_support_live_agent_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
    ]
