# Generated by Django 4.2.28 on 2026-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_livefeed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='app_description',
            field=models.TextField(blank=True, default='Official application for the Burundi Chairmanship 2026.', help_text='Description shown in the About dialog (English)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='app_description_fr',
            field=models.TextField(blank=True, default="Application officielle de la Présidence de l'Union Africaine du Burundi 2026.", help_text='Description shown in the About dialog (French)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='developer_name',
            field=models.CharField(blank=True, default='Eyosias Tamene', help_text='Developer/company name shown in About dialog', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='developer_url',
            field=models.URLField(blank=True, default='https://eyosias.dev', help_text='Developer website URL'),
        ),
    ]
