# Generated by Django 4.2.28 on 2026-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_about_fields_to_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(help_text='e.g. facebook, twitter, instagram, tiktok, threads, telegram, whatsapp', max_length=50, unique=True),
        ),
    ]
