# Generated by Django 4.2.28 on 2026-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_platform_choices_from_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_version',
            field=models.CharField(blank=True, help_text='App build version', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_os',
            field=models.CharField(blank=True, help_text='e.g. iOS 17.4, Android 14', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_type',
            field=models.CharField(blank=True, help_text='e.g. iPhone 15, Samsung Galaxy S24', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time user opened the app', null=True),
        ),
    ]
