# Generated by Django 4.2.28 on 2026-04-02 19:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_device_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Popup title', max_length=200)),
                ('title_fr', models.CharField(blank=True, help_text='French title', max_length=200)),
                ('message', models.TextField(help_text='Main message content')),
                ('message_fr', models.TextField(blank=True, help_text='French message')),
                ('image', models.ImageField(blank=True, help_text='Optional image displayed at top of popup', null=True, upload_to='popups/', validators=[core.validators.validate_image_file])),
                ('action_text', models.CharField(blank=True, help_text='Button text (e.g., "Click here", "Sign up now")', max_length=100)),
                ('action_text_fr', models.CharField(blank=True, help_text='French button text', max_length=100)),
                ('action_url', models.CharField(blank=True, help_text='URL or app route (e.g., "/events" or "https://external.com")', max_length=500)),
                ('popup_type', models.CharField(choices=[('general', 'General Announcement'), ('event', 'Event Promotion'), ('verification', 'Verification Reminder'), ('project', 'Project Update')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active popups are shown to users')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = shown first (0-100)')),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('verified_only', 'Verified Users Only'), ('unverified_only', 'Unverified Users Only')], default='all', max_length=20)),
                ('show_once', models.BooleanField(default=True, help_text='If true, user sees this popup only once')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Popup will not show after this date/time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup/Announcement',
                'verbose_name_plural': 'Popups/Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
