# Generated by Django 4.2.28 on 2026-04-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_popup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='target_audience',
        ),
    ]
