# Generated by Django 4.2.28 on 2026-04-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_popup_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='other_social_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='youtube_url',
        ),
        migrations.CreateModel(
            name='VerificationSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('threads', 'Threads'), ('other', 'Other')], help_text='Social media platform', max_length=20)),
                ('username_or_url', models.CharField(help_text='Username (e.g. @john_doe) or full URL (e.g. https://twitter.com/john_doe)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(help_text='The verification request this social media profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='core.verificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Social Media',
                'verbose_name_plural': 'Verification Social Media',
                'ordering': ['platform'],
                'unique_together': {('verification_request', 'platform')},
            },
        ),
    ]
