# Generated by Django 4.2.28 on 2026-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_backfill_article_like_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='core_userse_country_060591_idx',
            old_name='core_userse_country_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='core_userse_user_na_65f281_idx',
            old_name='core_userse_user_na_idx',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(max_length=20),
        ),
    ]
