# Generated by Django 4.2.28 on 2026-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_fix_otp_code_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_language',
            field=models.CharField(blank=True, choices=[('', 'All Languages'), ('en', 'English Only'), ('fr', 'French Only')], default='', help_text='Send only to users with this language preference', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text='Preferred language for push notifications', max_length=5),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Applicant gender', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='supporting_document',
            field=models.ImageField(blank=True, help_text='Optional supporting document or photo', null=True, upload_to='verification_documents/'),
        ),
    ]
