# Generated by Django 4.2.28 on 2026-04-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0065_seed_onboarding_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('throttle_class', models.CharField(blank=True, help_text='DRF throttle class that triggered the block', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_method', models.CharField(max_length=10)),
                ('was_blocked', models.BooleanField(default=True, help_text='True if request was rejected (429)')),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Log',
                'verbose_name_plural': 'Rate Limit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='core_articl_publish_031607_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', '-publish_date'], name='core_articl_is_feat_59982b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'event_date'], name='core_event_is_acti_f30b04_idx'),
        ),
        migrations.AddIndex(
            model_name='livefeed',
            index=models.Index(fields=['status', '-created_at'], name='core_livefe_status_0293ce_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineedition',
            index=models.Index(fields=['-publish_date'], name='core_magazi_publish_a70466_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineedition',
            index=models.Index(fields=['is_featured', '-publish_date'], name='core_magazi_is_feat_44cba1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'is_global', '-created_at'], name='core_notifi_is_acti_15e2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-updated_at'], name='core_suppor_status_38b78a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['is_admin_reply', 'is_read'], name='core_ticket_is_admi_f8837c_idx'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_limit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['-timestamp', 'ip_address'], name='core_rateli_timesta_df280a_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['-timestamp', 'endpoint'], name='core_rateli_timesta_029a1d_idx'),
        ),
    ]
