# Generated by Django 4.2.28 on 2026-04-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_add_rate_limit_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcementbanner',
            index=models.Index(fields=['is_active', '-priority', '-created_at'], name='core_announ_is_acti_1a00f4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='core_conver_last_me_477a06_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='core_direct_is_read_b0d1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['category', '-is_pinned', '-last_reply_at'], name='core_discus_categor_333dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['-is_pinned', '-last_reply_at', '-created_at'], name='core_discus_is_pinn_fe20ca_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['is_active', 'order', '-created_at'], name='core_eventr_is_acti_bf4552_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['sent', 'reminder_time'], name='core_eventr_sent_3a03fa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='core_events_status_4bf489_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubmission',
            index=models.Index(fields=['is_proxy', '-submitted_at'], name='core_events_is_prox_518f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['-is_featured', 'display_order', '-created_at'], name='core_galler_is_feat_ad80d8_idx'),
        ),
        migrations.AddIndex(
            model_name='popup',
            index=models.Index(fields=['is_active', '-priority', '-created_at'], name='core_popup_is_acti_e7da4a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmaintenance',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='core_schedu_is_acti_01288a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', '-created_at'], name='core_verifi_status_696a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-is_featured', '-publish_date'], name='core_video_is_feat_95a27b_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', '-publish_date'], name='core_video_categor_4b0b63_idx'),
        ),
    ]
