# Generated by Django 4.2.28 on 2026-04-08 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0067_add_database_indexes_for_query_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='affected_services',
            field=models.CharField(blank=True, default='all', help_text='Comma-separated list of affected services', max_length=200),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='auto_activate',
            field=models.BooleanField(default=False, help_text='Automatically enable maintenance at start time'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for users during maintenance', max_length=254),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('bulk_action', 'Bulk Action')], max_length=20)),
                ('model_name', models.CharField(blank=True, help_text='e.g. Article, User, Event', max_length=100)),
                ('object_id', models.IntegerField(blank=True, help_text='PK of the affected object', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of field changes {field: {old: x, new: y}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, help_text='Request URL path', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_admina_timesta_168ff2_idx'), models.Index(fields=['user', '-timestamp'], name='core_admina_user_id_1b952e_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_admina_action__01e91e_idx')],
            },
        ),
    ]
