# Generated by Django 4.2.28 on 2026-04-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0068_add_maintenance_severity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='JSON filter criteria: nationality, gender, badge_type, age_range, registered_after/before, has_verified_email, is_active')),
                ('is_dynamic', models.BooleanField(default=True, help_text='Dynamic segments recalculate members from filters on every access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Segment',
                'verbose_name_plural': 'User Segments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('data_only', 'Data Only'), ('schema_only', 'Schema Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_ticket', 'New Support Ticket'), ('new_verification', 'New Verification Request'), ('new_user', 'New User Registration'), ('ticket_reply', 'Ticket Reply'), ('system_alert', 'System Alert'), ('content_flagged', 'Content Flagged')], help_text='Category of admin notification', max_length=20)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification detail message')),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('icon', models.CharField(default='notifications', help_text='Material Symbols icon name', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='core_adminn_is_read_9f75fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.usersegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segment Membership',
                'verbose_name_plural': 'Segment Memberships',
                'ordering': ['-added_at'],
                'unique_together': {('segment', 'user')},
            },
        ),
    ]
