# Generated by Django 4.2.28 on 2026-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_seed_default_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='abtest',
            name='test_type',
            field=models.CharField(choices=[('content', 'Content'), ('layout', 'Layout'), ('feature', 'Feature Flag'), ('notification', 'Notification')], default='content', max_length=20),
        ),
        migrations.AddField(
            model_name='abtest',
            name='variant_a_content_id',
            field=models.PositiveIntegerField(blank=True, help_text='Content ID for variant A', null=True),
        ),
        migrations.AddField(
            model_name='abtest',
            name='variant_b_content_id',
            field=models.PositiveIntegerField(blank=True, help_text='Content ID for variant B', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers as key-value pairs'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='service_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True),
        ),
    ]
