# Generated by Django 4.2.28 on 2026-04-08 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0071_abtest_status_abtest_test_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Edition',
                'verbose_name_plural': 'Newsletter Editions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When the recurring series ends', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='Recurrence pattern for the event', max_length=10),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When attendee was checked in via QR', null=True),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='is_waitlisted',
            field=models.BooleanField(default=False, help_text='True if placed on waitlist due to full capacity'),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='qr_ticket_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for QR ticket validation', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Schedule notification for a future date/time. Leave blank to send immediately.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receives_newsletter',
            field=models.BooleanField(default=True, help_text='User opted in for weekly newsletter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications for VIP/Government users'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Auto-approved; admin can revoke'),
        ),
        migrations.CreateModel(
            name='VideoChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='Chapter start time in seconds')),
                ('order', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.video')),
            ],
            options={
                'verbose_name': 'Video Chapter',
                'verbose_name_plural': 'Video Chapters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('event', 'Event'), ('feature_card', 'Feature Card'), ('notification', 'Notification'), ('magazine', 'Magazine'), ('resource', 'Resource')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('source_language', models.CharField(default='en', max_length=5)),
                ('target_language', models.CharField(default='fr', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Request',
                'verbose_name_plural': 'Translation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.event')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.eventcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Comment',
                'verbose_name_plural': 'Event Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.eventcomment')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Mention',
                'verbose_name_plural': 'Comment Mentions',
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.article')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Revision',
                'verbose_name_plural': 'Article Revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=5)),
                ('subtitle_file', models.FileField(help_text='Upload .srt or .vtt subtitle file', upload_to='subtitles/')),
                ('is_default', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='core.video')),
            ],
            options={
                'verbose_name': 'Video Subtitle',
                'verbose_name_plural': 'Video Subtitles',
                'unique_together': {('video', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['event', '-created_at'], name='core_eventc_event_i_9bc5b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentmention',
            unique_together={('comment', 'mentioned_user')},
        ),
        migrations.AlterUniqueTogether(
            name='articlerevision',
            unique_together={('article', 'revision_number')},
        ),
    ]
