# Generated by Django 4.2.28 on 2026-04-08 20:32

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_newsletteredition_event_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=200)),
                ('track', models.CharField(blank=True, help_text='Track name for multi-track events', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event Agenda Item',
                'verbose_name_plural': 'Event Agenda Items',
                'ordering': ['start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_fr', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='podcasts/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcast_covers/', validators=[core.validators.validate_image_file])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('episode_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-archive article after this date. Expired articles are hidden from public API but remain in the database.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft articles are hidden from the public API until published.'),
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule article for future publication. If set and in the future, article is hidden from public API.', null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_draft', '-publish_date'], name='core_articl_is_draf_9d2793_idx'),
        ),
        migrations.AddField(
            model_name='eventagendaitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventagendaitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='core.eventspeaker'),
        ),
    ]
