# Generated by Django 4.2.28 on 2026-04-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_eventagendaitem_podcast_article_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
