# Generated by Django 4.2.28 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_podcast_model'),
    ]

    operations = [
        # Expand action_type max_length to accommodate new choices
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('create', 'Create'),
                    ('update', 'Update'),
                    ('delete', 'Delete'),
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('export', 'Export'),
                    ('approve', 'Approve'),
                    ('reject', 'Reject'),
                    ('bulk_action', 'Bulk Action'),
                    ('status_change', 'Status Change'),
                    ('send_notification', 'Send Notification'),
                    ('backup', 'Backup'),
                ],
                max_length=30,
            ),
        ),
    ]
