# Generated by Django 4.2.28 on 2026-04-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0075_notification_scheduling_devicetoken_opentracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('apple', 'Apple'), ('firebase', 'Firebase')], max_length=20)),
                ('provider_uid', models.CharField(help_text='Unique user ID from the auth provider', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary auth method')),
            ],
            options={
                'verbose_name': 'Linked Account',
                'verbose_name_plural': 'Linked Accounts',
                'ordering': ['-is_primary', '-linked_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='videochapter',
            options={'ordering': ['timestamp_seconds'], 'verbose_name': 'Video Chapter', 'verbose_name_plural': 'Video Chapters'},
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='core_device_is_acti_614700_idx',
            old_name='core_device_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_is_sche_2dcd9d_idx',
            old_name='core_notifi_is_sche_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this article (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this event (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this album (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Publishing workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this live feed (used when content_status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this magazine (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='magazineedition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this resource (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this video (used when status=scheduled)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Content workflow status: draft, scheduled, published, or archived', max_length=20),
        ),
        migrations.AddField(
            model_name='videochapter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videochapter',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videochapter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_chapters/'),
        ),
        migrations.AddField(
            model_name='videochapter',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('bulk_action', 'Bulk Action'), ('status_change', 'Status Change'), ('send_notification', 'Send Notification'), ('backup', 'Backup')], max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Legacy: Draft articles are hidden from the public API until published.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Legacy: Schedule article for future publication. If set and in the future, article is hidden from public API.', null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-publish_date'], name='core_articl_status_21a848_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='core_event_status_0790c8_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['status'], name='core_galler_status_d68501_idx'),
        ),
        migrations.AddIndex(
            model_name='livefeed',
            index=models.Index(fields=['content_status', '-created_at'], name='core_livefe_content_561ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineedition',
            index=models.Index(fields=['status', '-publish_date'], name='core_magazi_status_fce293_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='core_resour_status_1312f1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', '-publish_date'], name='core_video_status_0cf037_idx'),
        ),
        migrations.AddField(
            model_name='linkedaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='linkedaccount',
            unique_together={('provider', 'provider_uid')},
        ),
    ]
