# Generated by Django 4.2.28 on 2026-04-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_enhance_admin_activity_log_audit_trail'),
        ('core', '0076_linkedaccount'),
    ]

    operations = [
    ]
