# Generated by Django 4.2.28 on 2026-04-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_merge_20260408_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementbanner',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcementbanner',
            name='link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='announcementbanner',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='announcementbanner',
            name='title_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactdirectory',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactdirectory',
            name='department_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactdirectory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactdirectory',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactdirectory',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='topic',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='topic_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='polloption',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='banner_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('urgent', 'Urgent')], default='info', max_length=10),
        ),
    ]
