# Generated by Django 4.2.28 on 2026-04-09 08:14

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0078_announcementbanner_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(help_text='FCM registration token', max_length=255, unique=True, validators=[core.validators.validate_fcm_token]),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
