# Generated by Django 4.2.28 on 2026-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_allow_anonymous_device_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='bookmarks_enabled',
            field=models.BooleanField(default=True, help_text='Show Bookmarks feature in the app'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='discussions_enabled',
            field=models.BooleanField(default=True, help_text='Show Discussions feature in the app'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='newsletter_enabled',
            field=models.BooleanField(default=True, help_text='Show Weekly Newsletter toggle in the app'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='polls_enabled',
            field=models.BooleanField(default=True, help_text='Show Polls feature in the app'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified'),
        ),
    ]
