# Generated by Django 4.2.28 on 2026-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_feature_toggles_to_appsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='sms_verification_enabled',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='whatsapp_verification_enabled',
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='image',
            field=models.ImageField(blank=True, help_text='Full-screen image shown in the app during maintenance', null=True, upload_to='maintenance/'),
        ),
    ]
