# Generated by Django 4.2.28 on 2026-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_add_maintenance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online / Webinar'), ('hybrid', 'Hybrid'), ('info', 'Information Only')], default='in_person', max_length=20),
        ),
    ]
