# Generated by Django 4.2.28 on 2026-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_add_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='show_attendees',
            field=models.BooleanField(default=True, help_text='Show attendee list & count'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='show_comments',
            field=models.BooleanField(default=True, help_text='Allow comments/discussion'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='show_photos',
            field=models.BooleanField(default=True, help_text='Allow attendees to upload & view photos'),
        ),
    ]
