# Generated by Django 4.2.28 on 2026-04-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_add_event_feature_toggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('icon_name', models.CharField(default='event', help_text='Material icon name', max_length=50)),
                ('color', models.CharField(default='#1B5E20', help_text='Hex color', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventcategory'),
        ),
    ]
