# Generated by Django 4.2.28 on 2026-04-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0085_seed_event_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('delivered', 'Delivered'), ('displayed', 'Displayed'), ('opened', 'Opened'), ('dismissed', 'Dismissed')], max_length=20)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='core.devicetoken')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
                'indexes': [models.Index(fields=['notification', 'event_type'], name='core_notifi_notific_eccc9e_idx'), models.Index(fields=['created_at'], name='core_notifi_created_35b282_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.UniqueConstraint(fields=('notification', 'user', 'device_token', 'event_type'), name='unique_notif_event_per_recipient'),
        ),
    ]
