# Generated by Django 4.2.28 on 2026-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_add_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', help_text='Language for push notifications on this device (en/fr). Used to target anonymous devices that have not logged in yet.', max_length=5),
        ),
    ]
