# Generated by Django 4.2.28 on 2026-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_add_device_token_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_recipient_en',
            field=models.IntegerField(default=0, help_text='Number of devices that received the English version'),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_recipient_fr',
            field=models.IntegerField(default=0, help_text='Number of devices that received the French version'),
        ),
    ]
