# Generated by Django 4.2.28 on 2026-04-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0088_add_notification_language_recipient_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article Comment Mention',
                'verbose_name_plural': 'Article Comment Mentions',
            },
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threaded replies (1 level deep).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.articlecomment'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article', '-created_at'], name='core_articl_article_9fdbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['parent'], name='core_articl_parent__af0e54_idx'),
        ),
        migrations.AddField(
            model_name='articlecommentmention',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.articlecomment'),
        ),
        migrations.AddField(
            model_name='articlecommentmention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentmention',
            unique_together={('comment', 'mentioned_user')},
        ),
    ]
