# Generated by Django 4.2.28 on 2026-04-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_articlecommentmention_articlecomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='is_published',
            field=models.BooleanField(default=True, help_text='When unchecked, the popup is hidden from users even if the version matches.'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='popup_delay_seconds',
            field=models.PositiveIntegerField(default=2, help_text="How many seconds after app launch to show the What's New popup (0 = immediately)."),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='release_notes',
            field=models.TextField(blank=True, help_text='Optional free-form summary (deprecated in favor of highlights)'),
        ),
        migrations.CreateModel(
            name='AppReleaseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = shown first).')),
                ('icon_name', models.CharField(default='star_rounded', help_text='Material icon name (e.g. "forum_rounded", "notifications_active_rounded").', max_length=60)),
                ('title_en', models.CharField(max_length=120)),
                ('title_fr', models.CharField(blank=True, max_length=120)),
                ('subtitle_en', models.TextField()),
                ('subtitle_fr', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.apprelease')),
            ],
            options={
                'verbose_name': 'App Release Highlight',
                'verbose_name_plural': 'App Release Highlights',
                'ordering': ['order', 'id'],
            },
        ),
    ]
