# Generated by Django 4.2.28 on 2026-04-11 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0090_apprelease_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal campaign name', max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('subject_fr', models.CharField(blank=True, max_length=200)),
                ('body_html', models.TextField(help_text='HTML body. Use {{ user_name }} and {{ user_email }} as placeholders.')),
                ('body_html_fr', models.TextField(blank=True)),
                ('audience_type', models.CharField(choices=[('all', 'All active users'), ('language', 'By preferred language'), ('nationality', 'By nationality'), ('verified', 'Verified users only'), ('staff', 'Staff / admins only'), ('custom', 'Custom email list')], default='all', max_length=20)),
                ('audience_language', models.CharField(blank=True, help_text="When audience_type='language'", max_length=5)),
                ('audience_nationality', models.CharField(blank=True, help_text="When audience_type='nationality' (ISO code)", max_length=5)),
                ('custom_recipients', models.TextField(blank=True, help_text='Comma- or newline-separated email list (for custom audience)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('recipients', models.TextField(help_text='Comma-separated recipient emails')),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('campaign', 'Campaign'), ('verification', 'Verification'), ('otp', 'OTP / Login'), ('event', 'Event'), ('support', 'Support'), ('system', 'System'), ('test', 'Test / Preview'), ('other', 'Other')], default='other', max_length=20)),
                ('body_preview', models.TextField(blank=True, help_text='First ~500 chars of HTML or text body')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.emailcampaign')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_emaill_status_45c927_idx'), models.Index(fields=['category', 'created_at'], name='core_emaill_categor_28029d_idx')],
            },
        ),
    ]
