# Generated by Django 4.2.28 on 2026-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_emailcampaign_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_sections',
            field=models.JSONField(blank=True, default=list, help_text='List of admin section keys this staff user can access. Ignored for superusers.'),
        ),
    ]
