# Generated by Django 4.2.28 on 2026-04-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_userprofile_admin_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='event',
            field=models.ForeignKey(blank=True, help_text="Optional — link this webinar to an event so it inherits the event's speakers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_feeds', to='core.event'),
        ),
    ]
