# Generated by Django 4.2.28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0093_livefeed_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.magazineedition')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies (1 level deep).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.magazinecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['edition', '-created_at'], name='core_magazi_edition_idx'),
                    models.Index(fields=['parent'], name='core_magazi_parent__idx'),
                ],
            },
        ),
    ]
