# Generated by Django 4.2.28 on 2026-05-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0094_magazinecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Anonymous device identifier for guest tracking', max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_os', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='magazinecomment',
            new_name='core_magazi_edition_02069c_idx',
            old_name='core_magazi_edition_idx',
        ),
        migrations.RenameIndex(
            model_name='magazinecomment',
            new_name='core_magazi_parent__fc5266_idx',
            old_name='core_magazi_parent__idx',
        ),
        migrations.AddField(
            model_name='discussion',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='audience_type',
            field=models.CharField(choices=[('all', 'All active users'), ('newsletter', 'Newsletter subscribers'), ('language', 'By preferred language'), ('nationality', 'By nationality'), ('verified', 'Verified users only'), ('staff', 'Staff / admins only'), ('custom', 'Custom email list')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threaded replies (1 level deep).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.videocomment'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.video'),
        ),
        migrations.AddField(
            model_name='gallerycomment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.galleryalbum'),
        ),
        migrations.AddField(
            model_name='gallerycomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threaded replies (1 level deep).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.gallerycomment'),
        ),
        migrations.AddField(
            model_name='gallerycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlike',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionlike',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.discussion'),
        ),
        migrations.AddField(
            model_name='discussionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appopenevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_opens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['video', '-created_at'], name='core_videoc_video_i_de8a66_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['parent'], name='core_videoc_parent__6c889f_idx'),
        ),
        migrations.AddIndex(
            model_name='gallerycomment',
            index=models.Index(fields=['album', '-created_at'], name='core_galler_album_i_c6b9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gallerycomment',
            index=models.Index(fields=['parent'], name='core_galler_parent__4b58a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='discussionlike',
            unique_together={('user', 'discussion')},
        ),
        migrations.AddIndex(
            model_name='appopenevent',
            index=models.Index(fields=['-opened_at'], name='core_appope_opened__f053ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appopenevent',
            index=models.Index(fields=['user', '-opened_at'], name='core_appope_user_id_fbf910_idx'),
        ),
    ]
