# Generated by Django 4.2.28 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_add_engagement_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priorityagenda',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
