# Generated by Django 4.2.28 on 2026-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_articlecomment_like_count_articlecomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='max_length',
            field=models.IntegerField(blank=True, help_text='Maximum character length (for textarea)', null=True),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='min_length',
            field=models.IntegerField(blank=True, help_text='Minimum character length (for textarea)', null=True),
        ),
    ]
