# Generated by Django 4.2.28 on 2026-06-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0098_registrationformfield_max_length_min_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receives_newsletter',
            field=models.BooleanField(default=True, help_text='User opted in for monthly newsletter'),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to unsubscribe')),
                ('user', models.ForeignKey(blank=True, help_text='Linked app user (if subscribed while logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='newslettersubscriber',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_subscriber_email'),
        ),
    ]
