# Generated by Django 4.2.28 on 2026-06-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0099_newsletter_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthDialogueApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('he', 'H.E. (His/Her Excellency)'), ('amb', 'Ambassador'), ('hon', 'Honorable'), ('other', 'Other')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Contact email for this application', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('nationality', models.CharField(blank=True, choices=[('DZ', 'Algeria'), ('AO', 'Angola'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('CM', 'Cameroon'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('KM', 'Comoros'), ('CG', 'Congo (Brazzaville)'), ('CD', 'Congo (DRC)'), ('CI', "Côte d'Ivoire"), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GH', 'Ghana'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('ST', 'São Tomé and Príncipe'), ('SN', 'Senegal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('SS', 'South Sudan'), ('SD', 'Sudan'), ('TZ', 'Tanzania'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('UG', 'Uganda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CN', 'China'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('TR', 'Turkey'), ('AE', 'UAE'), ('GB', 'United Kingdom'), ('US', 'United States'), ('OTHER', 'Other')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('motivation', models.TextField(blank=True, help_text='Why the applicant wants to participate')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Flexible extra fields')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('documents_pending', 'Documents Pending'), ('documents_submitted', 'Documents Submitted'), ('documents_under_review', 'Documents Under Review'), ('documents_rejected', 'Documents Rejected'), ('credential_issued', 'Credential Issued')], default='submitted', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('documents_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('documents_rejection_notes', models.TextField(blank=True)),
                ('participant_code', models.CharField(blank=True, help_text='Format: YD-2026-0001', max_length=20, null=True, unique=True)),
                ('qr_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('credential_issued_at', models.DateTimeField(blank=True, null=True)),
                ('id_photo', models.ImageField(blank=True, help_text='Passport photo for ID card', null=True, upload_to='youth_dialogue/id_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yd_doc_reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yd_reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_dialogue_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Youth Dialogue Application',
                'verbose_name_plural': 'Youth Dialogue Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quickaccessmenuitem',
            name='visibility_rule',
            field=models.CharField(blank=True, choices=[('', 'Everyone'), ('youth_dialogue_accepted', 'Youth Dialogue Accepted Only')], default='', help_text='Who can see this menu item. Empty = everyone.', max_length=50),
        ),
        migrations.CreateModel(
            name='YouthDialogueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Copy'), ('national_id', 'National ID'), ('photo', 'Passport Photo'), ('cv', 'CV / Resume'), ('recommendation', 'Recommendation Letter'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='youth_dialogue/documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_resubmission', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.youthdialogueapplication')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='core.youthdialoguedocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yd_doc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Youth Dialogue Document',
                'verbose_name_plural': 'Youth Dialogue Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthDialogueActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('screen_visit', 'Screen Visit'), ('form_started', 'Form Started'), ('form_submitted', 'Form Submitted'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('status_viewed', 'Status Viewed'), ('credential_viewed', 'Credential Viewed'), ('credential_shared', 'Credential Shared'), ('qr_scanned', 'QR Scanned')], max_length=30)),
                ('screen_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.youthdialogueapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yd_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Youth Dialogue Activity Log',
                'verbose_name_plural': 'Youth Dialogue Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='youthdialogueapplication',
            index=models.Index(fields=['status', '-created_at'], name='core_youthd_status_919466_idx'),
        ),
        migrations.AddIndex(
            model_name='youthdialogueapplication',
            index=models.Index(fields=['email'], name='core_youthd_email_805b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='youthdialogueactivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='core_youthd_user_id_548f28_idx'),
        ),
        migrations.AddIndex(
            model_name='youthdialogueactivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='core_youthd_action_ee23cd_idx'),
        ),
    ]
