# Generated by Django 4.2.28 on 2026-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_youth_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('news', 'News')], default='article', help_text='Type of content: "article" for long-form articles, "news" for news items', max_length=10),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_type', '-publish_date'], name='core_articl_content_6d2828_idx'),
        ),
    ]
