# Generated by Django 4.2.28 on 2026-06-10 13:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_article_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstep',
            name='image_dark',
            field=models.ImageField(blank=True, help_text='Icon/logo for dark mode', upload_to='onboarding/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='onboardingstep',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Material icon name (fallback if no image)', max_length=50),
        ),
    ]
