# Generated by Django 4.2.28 on 2026-06-10 14:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_onboarding_image_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthDialogueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.ImageField(blank=True, help_text='Horizontal logo for light mode', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file])),
                ('logo_dark', models.ImageField(blank=True, help_text='Horizontal logo for dark mode', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file])),
                ('programme_title', models.CharField(default='Youth Dialogue Programme', max_length=200)),
                ('programme_title_fr', models.CharField(blank=True, default='Programme du Dialogue de la Jeunesse', max_length=200)),
                ('description', models.TextField(default="Join the African Union Youth Dialogue and contribute to shaping the continent's future. Apply now to participate in this prestigious programme.")),
                ('description_fr', models.TextField(blank=True, default="Rejoignez le Dialogue de la Jeunesse de l'Union Africaine et contribuez à façonner l'avenir du continent.")),
                ('is_registration_open', models.BooleanField(default=True, help_text='Whether new applications are accepted')),
                ('registration_closed_message', models.TextField(blank=True, default='Registration is currently closed. Please check back later.')),
                ('registration_closed_message_fr', models.TextField(blank=True, default='Les inscriptions sont actuellement fermées. Veuillez réessayer plus tard.')),
                ('support_email', models.EmailField(blank=True, default='', help_text='Contact email for Youth Dialogue support', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=30)),
                ('live_chat_url', models.URLField(blank=True, default='', help_text='URL for live chat support (e.g. WhatsApp, Tawk.to)')),
                ('support_note', models.TextField(blank=True, default='Need help? Reach out to our support team for assistance with your application.', help_text='Text shown above contact options')),
                ('support_note_fr', models.TextField(blank=True, default="Besoin d'aide ? Contactez notre équipe de support pour obtenir de l'aide avec votre candidature.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Youth Dialogue Settings',
                'verbose_name_plural': 'Youth Dialogue Settings',
            },
        ),
    ]
