# Generated by Django 4.2.28 on 2026-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_youth_dialogue_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold Badge'), ('BLUE', 'Blue Badge'), ('GREEN', 'Green Badge')], help_text='Type of verification badge (Gold for VIPs, Blue for officials, Green for verified users)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold Badge'), ('BLUE', 'Blue Badge'), ('GREEN', 'Green Badge')], help_text='Badge type assigned by admin (Gold or Blue)', max_length=10, null=True),
        ),
    ]
