# Generated by Django 4.2.28 on 2026-06-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_green_badge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='app_store_url',
            field=models.URLField(blank=True, default='https://apps.apple.com/app/id6740047505', help_text='Full App Store URL for iOS'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='play_store_url',
            field=models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.b4africa.app', help_text='Full Play Store URL for Android'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='app_store_id',
            field=models.CharField(blank=True, default='6740047505', help_text='App Store numeric ID', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='play_store_id',
            field=models.CharField(blank=True, default='com.b4africa.app', help_text='Play Store package name', max_length=100),
        ),
    ]
