# Generated by Django 4.2.28 on 2026-06-11 13:57

import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_hash_otp_code_at_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthDialogueMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('title_fr', models.CharField(blank=True, default='', max_length=200)),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('caption_fr', models.CharField(blank=True, default='', max_length=500)),
                ('edition_tag', models.CharField(blank=True, default='', help_text='e.g. "4th Edition 2025"', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='youth_dialogue/media/')),
                ('external_url', models.URLField(blank=True, default='', help_text='YouTube or Vimeo link for videos')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='youth_dialogue/media/thumbnails/')),
                ('is_promotional', models.BooleanField(default=False, help_text='Mark as main promotional video (only one allowed)')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Youth Dialogue Media',
                'verbose_name_plural': 'Youth Dialogue Media',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='promotionalsplash',
            new_name='core_promot_is_acti_40f1e3_idx',
            old_name='core_promot_is_acti_idx',
        ),
        migrations.AddField(
            model_name='youthdialogueapplication',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal admin notes (not visible to applicant)'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, storage=core.models._private_storage, upload_to='support/attachments/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='supporting_document',
            field=models.ImageField(blank=True, help_text='Optional supporting document or photo', null=True, storage=core.models._private_storage, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='youthdialogueapplication',
            name='id_photo',
            field=models.ImageField(blank=True, help_text='Passport photo for ID card', null=True, storage=core.models._private_storage, upload_to='youth_dialogue/id_photos/'),
        ),
        migrations.AlterField(
            model_name='youthdialoguedocument',
            name='file',
            field=models.FileField(storage=core.models._private_storage, upload_to='youth_dialogue/documents/'),
        ),
        migrations.AddField(
            model_name='youthdialoguemedia',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='core.youthdialoguesettings'),
        ),
    ]
