# Generated by Django 4.2.28 on 2026-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_eventsubmission_proxy_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueapplication',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youthdialogueapplication',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthdialogueapplication',
            name='revoked_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
