# Generated by Django 4.2.28 on 2026-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_youthdialogueapplication_is_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Require this user to change their password on next admin login'),
        ),
    ]
