# Generated by Django 4.2.28 on 2026-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_add_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecard',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('url', 'External URL'), ('route', 'App Route'), ('article', 'Article'), ('event', 'Event'), ('magazine', 'Magazine'), ('youth_dialogue', 'Youth Dialogue'), ('video', 'Video')], default='none', help_text='Leave as "No Action" to open detail page. Use URL/Route only for special redirects.', max_length=20),
        ),
    ]
