# Generated by Django 4.2.28 on 2026-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_feature_card_action_type_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['order', 'event_date', '-created_at'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='core_eventr_is_acti_bf4552_idx',
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['is_active', 'order', 'event_date', '-created_at'], name='core_eventr_is_acti_f8e39a_idx'),
        ),
    ]
