# Generated by Django 4.2.28 on 2026-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_youth_dialogue_multi_event_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qrscanlog',
            new_name='core_qrscan_qr_type_f560ce_idx',
            old_name='core_qrscan_qr_type_ref_idx',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='countdown_enabled',
            field=models.BooleanField(default=False, help_text='Show countdown on the home screen'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='countdown_label',
            field=models.CharField(blank=True, help_text='Countdown label in English (e.g. "AU Summit")', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='countdown_label_fr',
            field=models.CharField(blank=True, help_text='Countdown label in French', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='countdown_target_date',
            field=models.DateTimeField(blank=True, help_text='Target date/time for the home screen countdown', null=True),
        ),
        migrations.AlterField(
            model_name='qrscanlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
