# Generated by Django 4.2.28 on 2026-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_youth_dialogue_landing_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueevent',
            name='privacy_policy',
            field=models.TextField(blank=True, default='', help_text='Privacy policy text shown before application (EN)'),
        ),
        migrations.AddField(
            model_name='youthdialogueevent',
            name='privacy_policy_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deviceban',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profanitystrikelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
