# Generated by Django 4.2.28 on 2026-06-15 15:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_youthdialogueapplication_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueevent',
            name='logo_dark_fr',
            field=models.ImageField(blank=True, help_text='Programme logo — French (dark mode)', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='youthdialogueevent',
            name='logo_light_fr',
            field=models.ImageField(blank=True, help_text='Programme logo — French (light mode)', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='youthdialogueevent',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required document types. Each item: {"key": "passport", "label": "Passport Copy", "label_fr": "Copie du Passeport"}'),
        ),
        migrations.AddField(
            model_name='youthdialogueevent',
            name='secondary_logo',
            field=models.ImageField(blank=True, help_text='Secondary logo (e.g. B4 Africa) — shown alongside programme logo', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Programme logo — English (dark mode)', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Programme logo — English (light mode)', upload_to='youth_dialogue/', validators=[core.validators.validate_image_file]),
        ),
    ]
