# Generated by Django 4.2.28 on 2026-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_yd_configurable_docs_and_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_usher',
            field=models.BooleanField(default=False, help_text='User can scan YD credentials at events'),
        ),
    ]
