# Generated by Django 4.2.28 on 2026-06-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_youth_dialogue_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthdialogueapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('moderator', 'Moderator'), ('technician', 'Technician'), ('scientific_committee', 'Scientific Committee'), ('panelist', 'Panelist'), ('partner', 'Partner'), ('participant', 'Participant'), ('guest_of_honor', 'Guest of Honor'), ('security', 'Security'), ('protocol', 'Protocol')], max_length=200),
        ),
        migrations.AlterField(
            model_name='youthdialoguerole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
