# Generated by Django 4.2.28 on 2026-06-24 17:41

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_add_position_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecardmedia',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, MOV, etc.), OR paste a URL below', upload_to='feature_card_media/videos/', validators=[core.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='promotionalsplash',
            name='image',
            field=models.ImageField(upload_to='promotional_splashes/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='image',
            field=models.ImageField(blank=True, help_text='Full-screen image shown in the app during maintenance', null=True, upload_to='maintenance/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, MOV, etc.) or leave empty if using URL', upload_to='videos/files/', validators=[core.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='subtitle_file',
            field=models.FileField(help_text='Upload .srt or .vtt subtitle file', upload_to='subtitles/', validators=[core.validators.validate_subtitle_file]),
        ),
        migrations.AlterField(
            model_name='youthdialoguedocument',
            name='file',
            field=models.FileField(storage=core.models._private_storage, upload_to='youth_dialogue/documents/', validators=[core.validators.validate_document_file]),
        ),
    ]
