# Generated by Django 4.2.28 on 2026-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_add_file_upload_validators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youthdialogueactivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Continental Dialogue Activity Log', 'verbose_name_plural': 'Continental Dialogue Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='youthdialogueapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Continental Dialogue Application', 'verbose_name_plural': 'Continental Dialogue Applications'},
        ),
        migrations.AlterModelOptions(
            name='youthdialoguedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Continental Dialogue Document', 'verbose_name_plural': 'Continental Dialogue Documents'},
        ),
        migrations.AlterModelOptions(
            name='youthdialogueevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Continental Dialogue Event', 'verbose_name_plural': 'Continental Dialogue Events'},
        ),
        migrations.AlterModelOptions(
            name='youthdialogueformfield',
            options={'ordering': ['order'], 'verbose_name': 'Continental Dialogue Form Field', 'verbose_name_plural': 'Continental Dialogue Form Fields'},
        ),
        migrations.AlterModelOptions(
            name='youthdialoguemedia',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Continental Dialogue Media', 'verbose_name_plural': 'Continental Dialogue Media'},
        ),
        migrations.AlterModelOptions(
            name='youthdialoguerole',
            options={'ordering': ['order'], 'verbose_name': 'Continental Dialogue Role', 'verbose_name_plural': 'Continental Dialogue Roles'},
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('url', 'External URL'), ('route', 'App Route'), ('article', 'Article'), ('event', 'Event'), ('magazine', 'Magazine'), ('youth_dialogue', 'Continental Dialogue'), ('video', 'Video')], default='none', help_text='Leave as "No Action" to open detail page. Use URL/Route only for special redirects.', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrscanlog',
            name='qr_type',
            field=models.CharField(choices=[('event', 'Event Ticket'), ('youth_dialogue', 'Continental Dialogue Credential')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quickaccessmenuitem',
            name='visibility_rule',
            field=models.CharField(blank=True, choices=[('', 'Everyone'), ('youth_dialogue_accepted', 'Continental Dialogue Accepted Only')], default='', help_text='Who can see this menu item. Empty = everyone.', max_length=50),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='description',
            field=models.TextField(default="Join the African Union Continental Dialogue and contribute to shaping the continent's future. Apply now to participate in this prestigious programme."),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='description_fr',
            field=models.TextField(blank=True, default="Rejoignez le Dialogue Continental de l'Union Africaine et contribuez à façonner l'avenir du continent."),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show Continental Dialogue in Quick Access grid'),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='programme_title',
            field=models.CharField(default='Continental Dialogue Programme', max_length=200),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='programme_title_fr',
            field=models.CharField(blank=True, default='Programme du Dialogue Continental', max_length=200),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='quick_access_title_en',
            field=models.CharField(blank=True, default='Continental Dialogue', help_text='Quick Access button title (EN)', max_length=50),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='quick_access_title_fr',
            field=models.CharField(blank=True, default='Dialogue Continental', help_text='Quick Access button title (FR)', max_length=50),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='support_email',
            field=models.EmailField(blank=True, default='', help_text='Contact email for Continental Dialogue support', max_length=254),
        ),
    ]
