# Generated by Django 4.2.28 on 2026-07-03 14:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_youthdialogueactivitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueevent',
            name='sponsors_image',
            field=models.ImageField(blank=True, help_text='Single merged image showing all sponsor/partner logos', null=True, upload_to='youth_dialogue/sponsors/', validators=[core.validators.validate_image_file]),
        ),
    ]
