# Generated by Django 4.2.28 on 2026-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_factcategory_fact_appsettings_facts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_platform',
            field=models.CharField(blank=True, choices=[('', 'All Platforms'), ('android', 'Android Only'), ('ios', 'iOS Only')], default='', help_text='Send only to devices on this platform', max_length=10),
        ),
    ]
