# Generated by Django 4.2.28 on 2026-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_notification_target_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='section_title_agendas',
            field=models.CharField(blank=True, default='Priority Agendas', help_text='Home section title for Priority Agendas (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_agendas_fr',
            field=models.CharField(blank=True, default='Agendas Prioritaires', help_text='Home section title for Priority Agendas (French)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_events',
            field=models.CharField(blank=True, default='Upcoming Events', help_text='Home section title for Events (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_events_fr',
            field=models.CharField(blank=True, default='Prochains Événements', help_text='Home section title for Events (French)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_facts',
            field=models.CharField(blank=True, default='Discover Africa', help_text='Home section title for Facts & Quotes (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_facts_fr',
            field=models.CharField(blank=True, default="Découvrir l'Afrique", help_text='Home section title for Facts & Quotes (French)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_magazines',
            field=models.CharField(blank=True, default='Latest Magazines', help_text='Home section title for Magazines (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_magazines_fr',
            field=models.CharField(blank=True, default='Derniers Magazines', help_text='Home section title for Magazines (French)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_news',
            field=models.CharField(blank=True, default='News', help_text='Home section title for News (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_news_fr',
            field=models.CharField(blank=True, default='Actualités', help_text='Home section title for News (French)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_trending',
            field=models.CharField(blank=True, default='Trending', help_text='Home section title for Trending (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='section_title_trending_fr',
            field=models.CharField(blank=True, default='Tendances', help_text='Home section title for Trending (French)', max_length=100),
        ),
    ]
