# Generated by Django 4.2.28 on 2026-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_add_section_title_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='live_feeds_enabled',
            field=models.BooleanField(default=True, help_text='Show Live Feeds feature in the app'),
        ),
    ]
