# Generated by Django 4.2.28 on 2026-07-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_allow_reapply_after_revocation'),
        ('core', '0141_quickaccessmenuitem_icon_image'),
    ]

    operations = [
    ]
