# Generated by Django 4.2.28 on 2026-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_merge_20260708_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
