# Generated by Django 4.2.28 on 2026-07-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_youthdialogueevent_key_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthdialoguedeviceban',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='youthdialoguesideevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
