# Generated by Django 4.2.28 on 2026-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_youthdialogueevent_field_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greetings', 'Greetings'), ('directions', 'Directions'), ('diplomacy', 'Diplomacy'), ('numbers', 'Numbers'), ('food', 'Food & Drink'), ('travel', 'Travel'), ('culture', 'Culture'), ('business', 'Business')], db_index=True, max_length=50)),
                ('category_icon', models.CharField(blank=True, help_text='Material icon name (auto-filled if blank)', max_length=50)),
                ('kirundi', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('french', models.CharField(max_length=300)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Phrasebook entries',
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
    ]
