# Generated by Django 4.2.28 on 2026-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_appsettings_developer_role_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System')], default='manual', max_length=10),
        ),
    ]
