# Generated by Django 4.2.28 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_add_notification_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueevent',
            name='scanner_title_en',
            field=models.CharField(blank=True, default='', help_text='Scanner screen title (English). Falls back to quick access title if blank.', max_length=100),
        ),
        migrations.AddField(
            model_name='youthdialogueevent',
            name='scanner_title_fr',
            field=models.CharField(blank=True, default='', help_text='Scanner screen title (French). Falls back to quick access title if blank.', max_length=100),
        ),
    ]
