# Generated by Django 4.2.28 on 2026-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_expand_nationality_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformfield',
            name='help_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='help_text_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='event_tagline',
            field=models.TextField(blank=True, default='', help_text='Short tagline shown below title'),
        ),
        migrations.AlterField(
            model_name='youthdialogueevent',
            name='event_tagline_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='youthdialogueformfield',
            name='help_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='youthdialogueformfield',
            name='help_text_fr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
