# Generated by Django 4.2.28 on 2026-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_remove_varchar300_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.URLField(blank=True, default='', help_text='Google Maps link for the venue', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
