from django.db import migrations


def seed_phrasebook(apps, schema_editor):
    PhrasebookEntry = apps.get_model('core', 'PhrasebookEntry')

    entries = [
        # ════════════════════════════════════════
        # ── GREETINGS & BASIC EXPRESSIONS ──
        # ════════════════════════════════════════
        {'category': 'greetings', 'kirundi': 'Amahoro', 'english': 'Hello / Peace', 'french': 'Bonjour / Paix', 'display_order': 1},
        {'category': 'greetings', 'kirundi': 'Bite?', 'english': 'How are you?', 'french': 'Comment allez-vous ?', 'display_order': 2},
        {'category': 'greetings', 'kirundi': 'Ni vyiza', 'english': 'I am fine', 'french': 'Je vais bien', 'display_order': 3},
        {'category': 'greetings', 'kirundi': 'Ni vyiza cane', 'english': 'I am very well', 'french': 'Je vais très bien', 'display_order': 4},
        {'category': 'greetings', 'kirundi': 'Ego', 'english': 'Yes', 'french': 'Oui', 'display_order': 5},
        {'category': 'greetings', 'kirundi': 'Oya', 'english': 'No', 'french': 'Non', 'display_order': 6},
        {'category': 'greetings', 'kirundi': 'Urakoze', 'english': 'Thank you', 'french': 'Merci', 'display_order': 7},
        {'category': 'greetings', 'kirundi': 'Urakoze cane', 'english': 'Thank you very much', 'french': 'Merci beaucoup', 'display_order': 8},
        {'category': 'greetings', 'kirundi': 'Murakoze', 'english': 'Thank you (plural/formal)', 'french': 'Merci (pluriel/formel)', 'display_order': 9},
        {'category': 'greetings', 'kirundi': 'Murakaza neza', 'english': 'Welcome', 'french': 'Bienvenue', 'display_order': 10},
        {'category': 'greetings', 'kirundi': 'Buraho', 'english': 'Goodbye', 'french': 'Au revoir', 'display_order': 11},
        {'category': 'greetings', 'kirundi': 'Turabonana', 'english': 'See you later', 'french': 'À bientôt', 'display_order': 12},
        {'category': 'greetings', 'kirundi': 'Turabonana ejo', 'english': 'See you tomorrow', 'french': 'À demain', 'display_order': 13},
        {'category': 'greetings', 'kirundi': 'Ni joro nziza', 'english': 'Good evening', 'french': 'Bonsoir', 'display_order': 14},
        {'category': 'greetings', 'kirundi': 'Bwakeye', 'english': 'Good morning', 'french': 'Bonjour (matin)', 'display_order': 15},
        {'category': 'greetings', 'kirundi': 'Ijoro ryiza', 'english': 'Good night', 'french': 'Bonne nuit', 'display_order': 16},
        {'category': 'greetings', 'kirundi': 'Ndagukunda', 'english': 'I love you', 'french': 'Je t\'aime', 'display_order': 17},
        {'category': 'greetings', 'kirundi': 'Ikibazo ni iki?', 'english': 'What is the problem?', 'french': 'Quel est le problème ?', 'display_order': 18},
        {'category': 'greetings', 'kirundi': 'Ntimbishoboka', 'english': 'It is not possible', 'french': 'Ce n\'est pas possible', 'display_order': 19},
        {'category': 'greetings', 'kirundi': 'Birashoboka', 'english': 'It is possible', 'french': 'C\'est possible', 'display_order': 20},
        {'category': 'greetings', 'kirundi': 'Mbabarira', 'english': 'Excuse me / I am sorry', 'french': 'Excusez-moi / Pardon', 'display_order': 21},
        {'category': 'greetings', 'kirundi': 'Ndabimenye', 'english': 'I understand', 'french': 'Je comprends', 'display_order': 22},
        {'category': 'greetings', 'kirundi': 'Sinumva', 'english': 'I don\'t understand', 'french': 'Je ne comprends pas', 'display_order': 23},
        {'category': 'greetings', 'kirundi': 'Wivuze iki?', 'english': 'What did you say?', 'french': 'Qu\'avez-vous dit ?', 'display_order': 24},
        {'category': 'greetings', 'kirundi': 'Subiramo', 'english': 'Please repeat', 'french': 'Répétez s\'il vous plaît', 'display_order': 25},
        {'category': 'greetings', 'kirundi': 'Vuga buhoro', 'english': 'Speak slowly', 'french': 'Parlez lentement', 'display_order': 26},
        {'category': 'greetings', 'kirundi': 'Uvuga icongereza?', 'english': 'Do you speak English?', 'french': 'Parlez-vous anglais ?', 'display_order': 27},
        {'category': 'greetings', 'kirundi': 'Uvuga igifaransa?', 'english': 'Do you speak French?', 'french': 'Parlez-vous français ?', 'display_order': 28},
        {'category': 'greetings', 'kirundi': 'Uvuga ikirundi?', 'english': 'Do you speak Kirundi?', 'french': 'Parlez-vous kirundi ?', 'display_order': 29},
        {'category': 'greetings', 'kirundi': 'Ndavuga ikirundi gato', 'english': 'I speak a little Kirundi', 'french': 'Je parle un peu kirundi', 'display_order': 30},
        {'category': 'greetings', 'kirundi': 'Izina ryawe ni nde?', 'english': 'What is your name?', 'french': 'Comment vous appelez-vous ?', 'display_order': 31},
        {'category': 'greetings', 'kirundi': 'Izina ryanje ni ...', 'english': 'My name is ...', 'french': 'Je m\'appelle ...', 'display_order': 32},
        {'category': 'greetings', 'kirundi': 'Uva mu gihugu ikihe?', 'english': 'What country are you from?', 'french': 'De quel pays venez-vous ?', 'display_order': 33},
        {'category': 'greetings', 'kirundi': 'Nva mu ...', 'english': 'I come from ...', 'french': 'Je viens de ...', 'display_order': 34},
        {'category': 'greetings', 'kirundi': 'Ndakeneye ubufasha', 'english': 'I need help', 'french': 'J\'ai besoin d\'aide', 'display_order': 35},
        {'category': 'greetings', 'kirundi': 'Umunsi mwiza', 'english': 'Have a nice day', 'french': 'Bonne journée', 'display_order': 36},
        {'category': 'greetings', 'kirundi': 'Imana ibarinde', 'english': 'God bless you', 'french': 'Que Dieu vous bénisse', 'display_order': 37},
        {'category': 'greetings', 'kirundi': 'Ntabwo ari vyinshi', 'english': 'You are welcome / It\'s nothing', 'french': 'De rien', 'display_order': 38},
        {'category': 'greetings', 'kirundi': 'Ni kuki?', 'english': 'Why?', 'french': 'Pourquoi ?', 'display_order': 39},
        {'category': 'greetings', 'kirundi': 'Ni ryari?', 'english': 'When?', 'french': 'Quand ?', 'display_order': 40},
        {'category': 'greetings', 'kirundi': 'Ni nde?', 'english': 'Who?', 'french': 'Qui ?', 'display_order': 41},
        {'category': 'greetings', 'kirundi': 'Ni iki?', 'english': 'What?', 'french': 'Quoi ?', 'display_order': 42},
        {'category': 'greetings', 'kirundi': 'Gute?', 'english': 'How?', 'french': 'Comment ?', 'display_order': 43},
        {'category': 'greetings', 'kirundi': 'Ni hehe?', 'english': 'Where?', 'french': 'Où ?', 'display_order': 44},
        {'category': 'greetings', 'kirundi': 'Ndagusavye', 'english': 'Please', 'french': 'S\'il vous plaît', 'display_order': 45},

        # ════════════════════════════════════════
        # ── DIRECTIONS & GETTING AROUND ──
        # ════════════════════════════════════════
        {'category': 'directions', 'kirundi': 'Iburyo', 'english': 'Right', 'french': 'Droite', 'display_order': 1},
        {'category': 'directions', 'kirundi': 'Ibubamfu', 'english': 'Left', 'french': 'Gauche', 'display_order': 2},
        {'category': 'directions', 'kirundi': 'Imbere', 'english': 'Straight ahead / In front', 'french': 'Tout droit / Devant', 'display_order': 3},
        {'category': 'directions', 'kirundi': 'Inyuma', 'english': 'Behind / Back', 'french': 'Derrière', 'display_order': 4},
        {'category': 'directions', 'kirundi': 'Hejuru', 'english': 'Up / Above', 'french': 'En haut', 'display_order': 5},
        {'category': 'directions', 'kirundi': 'Hasi', 'english': 'Down / Below', 'french': 'En bas', 'display_order': 6},
        {'category': 'directions', 'kirundi': 'Hafi', 'english': 'Near / Close', 'french': 'Près', 'display_order': 7},
        {'category': 'directions', 'kirundi': 'Kure', 'english': 'Far', 'french': 'Loin', 'display_order': 8},
        {'category': 'directions', 'kirundi': 'Hano', 'english': 'Here', 'french': 'Ici', 'display_order': 9},
        {'category': 'directions', 'kirundi': 'Hariya', 'english': 'There / Over there', 'french': 'Là-bas', 'display_order': 10},
        {'category': 'directions', 'kirundi': 'Hagati', 'english': 'In the middle / Between', 'french': 'Au milieu / Entre', 'display_order': 11},
        {'category': 'directions', 'kirundi': 'Iruhande', 'english': 'Beside / Next to', 'french': 'À côté de', 'display_order': 12},
        {'category': 'directions', 'kirundi': 'Mu nkengera', 'english': 'On the corner', 'french': 'Au coin', 'display_order': 13},
        {'category': 'directions', 'kirundi': 'Ni hehe ...?', 'english': 'Where is ...?', 'french': 'Où est ... ?', 'display_order': 14},
        {'category': 'directions', 'kirundi': 'Ni hehe aho tuja?', 'english': 'Where are we going?', 'french': 'Où allons-nous ?', 'display_order': 15},
        {'category': 'directions', 'kirundi': 'Ndashaka kuja ...', 'english': 'I want to go to ...', 'french': 'Je veux aller à ...', 'display_order': 16},
        {'category': 'directions', 'kirundi': 'Ni hehe ihoteli?', 'english': 'Where is the hotel?', 'french': 'Où est l\'hôtel ?', 'display_order': 17},
        {'category': 'directions', 'kirundi': 'Ni hehe ikibuga c\'indege?', 'english': 'Where is the airport?', 'french': 'Où est l\'aéroport ?', 'display_order': 18},
        {'category': 'directions', 'kirundi': 'Ni hehe ibitaro?', 'english': 'Where is the hospital?', 'french': 'Où est l\'hôpital ?', 'display_order': 19},
        {'category': 'directions', 'kirundi': 'Ni hehe ambasade?', 'english': 'Where is the embassy?', 'french': 'Où est l\'ambassade ?', 'display_order': 20},
        {'category': 'directions', 'kirundi': 'Ni hehe ibanki?', 'english': 'Where is the bank?', 'french': 'Où est la banque ?', 'display_order': 21},
        {'category': 'directions', 'kirundi': 'Ni hehe isoko?', 'english': 'Where is the market?', 'french': 'Où est le marché ?', 'display_order': 22},
        {'category': 'directions', 'kirundi': 'Ni hehe igare?', 'english': 'Where is the station?', 'french': 'Où est la gare ?', 'display_order': 23},
        {'category': 'directions', 'kirundi': 'Ni hehe iresitora?', 'english': 'Where is the restaurant?', 'french': 'Où est le restaurant ?', 'display_order': 24},
        {'category': 'directions', 'kirundi': 'Ni hehe inyubakwa y\'inama?', 'english': 'Where is the conference centre?', 'french': 'Où est le centre de conférence ?', 'display_order': 25},
        {'category': 'directions', 'kirundi': 'Ni hehe ubwirizabuguzi?', 'english': 'Where is the pharmacy?', 'french': 'Où est la pharmacie ?', 'display_order': 26},
        {'category': 'directions', 'kirundi': 'Ni hehe ikigo c\'igipolisi?', 'english': 'Where is the police station?', 'french': 'Où est le commissariat ?', 'display_order': 27},
        {'category': 'directions', 'kirundi': 'Hindura iburyo', 'english': 'Turn right', 'french': 'Tournez à droite', 'display_order': 28},
        {'category': 'directions', 'kirundi': 'Hindura ibubamfu', 'english': 'Turn left', 'french': 'Tournez à gauche', 'display_order': 29},
        {'category': 'directions', 'kirundi': 'Komeza imbere', 'english': 'Continue straight', 'french': 'Continuez tout droit', 'display_order': 30},
        {'category': 'directions', 'kirundi': 'Hagarara', 'english': 'Stop', 'french': 'Arrêtez', 'display_order': 31},
        {'category': 'directions', 'kirundi': 'Ni kure kangana?', 'english': 'How far is it?', 'french': 'C\'est à quelle distance ?', 'display_order': 32},
        {'category': 'directions', 'kirundi': 'Nshobora kugendayo n\'amaguru?', 'english': 'Can I walk there?', 'french': 'Puis-je y aller à pied ?', 'display_order': 33},
        {'category': 'directions', 'kirundi': 'Nyereka inzira', 'english': 'Show me the way', 'french': 'Montrez-moi le chemin', 'display_order': 34},
        {'category': 'directions', 'kirundi': 'Nabuze', 'english': 'I am lost', 'french': 'Je suis perdu(e)', 'display_order': 35},

        # ════════════════════════════════════════
        # ── DIPLOMACY & GOVERNANCE ──
        # ════════════════════════════════════════
        {'category': 'diplomacy', 'kirundi': 'Inama', 'english': 'Meeting / Council', 'french': 'Réunion / Conseil', 'display_order': 1},
        {'category': 'diplomacy', 'kirundi': 'Inama nkuru', 'english': 'Summit', 'french': 'Sommet', 'display_order': 2},
        {'category': 'diplomacy', 'kirundi': 'Amasezerano', 'english': 'Agreement / Treaty', 'french': 'Accord / Traité', 'display_order': 3},
        {'category': 'diplomacy', 'kirundi': 'Ubumwe', 'english': 'Unity', 'french': 'Unité', 'display_order': 4},
        {'category': 'diplomacy', 'kirundi': 'Iterambere', 'english': 'Development / Progress', 'french': 'Développement / Progrès', 'display_order': 5},
        {'category': 'diplomacy', 'kirundi': 'Ubutegetsi', 'english': 'Governance', 'french': 'Gouvernance', 'display_order': 6},
        {'category': 'diplomacy', 'kirundi': 'Amahoro n\'umutekano', 'english': 'Peace and security', 'french': 'Paix et sécurité', 'display_order': 7},
        {'category': 'diplomacy', 'kirundi': 'Umushikiranganji', 'english': 'Minister', 'french': 'Ministre', 'display_order': 8},
        {'category': 'diplomacy', 'kirundi': 'Umukuru w\'igihugu', 'english': 'Head of State / President', 'french': 'Chef d\'État / Président', 'display_order': 9},
        {'category': 'diplomacy', 'kirundi': 'Icegera c\'umukuru w\'igihugu', 'english': 'Vice President', 'french': 'Vice-Président', 'display_order': 10},
        {'category': 'diplomacy', 'kirundi': 'Umushikiranganji wa mbere', 'english': 'Prime Minister', 'french': 'Premier Ministre', 'display_order': 11},
        {'category': 'diplomacy', 'kirundi': 'Intumwa', 'english': 'Delegate / Envoy', 'french': 'Délégué / Envoyé', 'display_order': 12},
        {'category': 'diplomacy', 'kirundi': 'Ambasaderi', 'english': 'Ambassador', 'french': 'Ambassadeur', 'display_order': 13},
        {'category': 'diplomacy', 'kirundi': 'Ubufatanye', 'english': 'Cooperation', 'french': 'Coopération', 'display_order': 14},
        {'category': 'diplomacy', 'kirundi': 'Demokarasi', 'english': 'Democracy', 'french': 'Démocratie', 'display_order': 15},
        {'category': 'diplomacy', 'kirundi': 'Amatora', 'english': 'Elections', 'french': 'Élections', 'display_order': 16},
        {'category': 'diplomacy', 'kirundi': 'Ivyegeranyo', 'english': 'Report', 'french': 'Rapport', 'display_order': 17},
        {'category': 'diplomacy', 'kirundi': 'Ibwirizwa shingiro', 'english': 'Constitution', 'french': 'Constitution', 'display_order': 18},
        {'category': 'diplomacy', 'kirundi': 'Itegeko', 'english': 'Law', 'french': 'Loi', 'display_order': 19},
        {'category': 'diplomacy', 'kirundi': 'Uburenganzira bw\'ikiremwa muntu', 'english': 'Human rights', 'french': 'Droits de l\'homme', 'display_order': 20},
        {'category': 'diplomacy', 'kirundi': 'Ihuriro ry\'ubumwe bw\'Afurika', 'english': 'African Union', 'french': 'Union Africaine', 'display_order': 21},
        {'category': 'diplomacy', 'kirundi': 'Ubushikiranganji bw\'ababanyi', 'english': 'Foreign Affairs', 'french': 'Affaires étrangères', 'display_order': 22},
        {'category': 'diplomacy', 'kirundi': 'Amahoro arama', 'english': 'Lasting peace', 'french': 'Paix durable', 'display_order': 23},
        {'category': 'diplomacy', 'kirundi': 'Uguseranganya', 'english': 'Negotiation', 'french': 'Négociation', 'display_order': 24},
        {'category': 'diplomacy', 'kirundi': 'Ingingo', 'english': 'Resolution / Decision', 'french': 'Résolution / Décision', 'display_order': 25},
        {'category': 'diplomacy', 'kirundi': 'Ishirahamwe mpuzamakungu', 'english': 'International organization', 'french': 'Organisation internationale', 'display_order': 26},
        {'category': 'diplomacy', 'kirundi': 'Ishirahamwe ry\'abibumbye', 'english': 'United Nations', 'french': 'Nations Unies', 'display_order': 27},
        {'category': 'diplomacy', 'kirundi': 'Igihugu', 'english': 'Country / Nation', 'french': 'Pays / Nation', 'display_order': 28},
        {'category': 'diplomacy', 'kirundi': 'Akarere', 'english': 'Region / District', 'french': 'Région / District', 'display_order': 29},
        {'category': 'diplomacy', 'kirundi': 'Intara', 'english': 'Province', 'french': 'Province', 'display_order': 30},
        {'category': 'diplomacy', 'kirundi': 'Umuryango', 'english': 'Community / Family', 'french': 'Communauté / Famille', 'display_order': 31},
        {'category': 'diplomacy', 'kirundi': 'Ubwigenge', 'english': 'Independence', 'french': 'Indépendance', 'display_order': 32},
        {'category': 'diplomacy', 'kirundi': 'Umutekano', 'english': 'Security', 'french': 'Sécurité', 'display_order': 33},
        {'category': 'diplomacy', 'kirundi': 'Ubutungane', 'english': 'Justice', 'french': 'Justice', 'display_order': 34},
        {'category': 'diplomacy', 'kirundi': 'Igihugu c\'Uburundi', 'english': 'Republic of Burundi', 'french': 'République du Burundi', 'display_order': 35},

        # ════════════════════════════════════════
        # ── NUMBERS & COUNTING ──
        # ════════════════════════════════════════
        {'category': 'numbers', 'kirundi': 'Rimwe', 'english': 'One (1)', 'french': 'Un (1)', 'display_order': 1},
        {'category': 'numbers', 'kirundi': 'Kabiri', 'english': 'Two (2)', 'french': 'Deux (2)', 'display_order': 2},
        {'category': 'numbers', 'kirundi': 'Gatatu', 'english': 'Three (3)', 'french': 'Trois (3)', 'display_order': 3},
        {'category': 'numbers', 'kirundi': 'Kane', 'english': 'Four (4)', 'french': 'Quatre (4)', 'display_order': 4},
        {'category': 'numbers', 'kirundi': 'Gatanu', 'english': 'Five (5)', 'french': 'Cinq (5)', 'display_order': 5},
        {'category': 'numbers', 'kirundi': 'Gatandatu', 'english': 'Six (6)', 'french': 'Six (6)', 'display_order': 6},
        {'category': 'numbers', 'kirundi': 'Indwi', 'english': 'Seven (7)', 'french': 'Sept (7)', 'display_order': 7},
        {'category': 'numbers', 'kirundi': 'Umunani', 'english': 'Eight (8)', 'french': 'Huit (8)', 'display_order': 8},
        {'category': 'numbers', 'kirundi': 'Icenda', 'english': 'Nine (9)', 'french': 'Neuf (9)', 'display_order': 9},
        {'category': 'numbers', 'kirundi': 'Icumi', 'english': 'Ten (10)', 'french': 'Dix (10)', 'display_order': 10},
        {'category': 'numbers', 'kirundi': 'Icumi na rimwe', 'english': 'Eleven (11)', 'french': 'Onze (11)', 'display_order': 11},
        {'category': 'numbers', 'kirundi': 'Icumi na kabiri', 'english': 'Twelve (12)', 'french': 'Douze (12)', 'display_order': 12},
        {'category': 'numbers', 'kirundi': 'Icumi na gatatu', 'english': 'Thirteen (13)', 'french': 'Treize (13)', 'display_order': 13},
        {'category': 'numbers', 'kirundi': 'Icumi na kane', 'english': 'Fourteen (14)', 'french': 'Quatorze (14)', 'display_order': 14},
        {'category': 'numbers', 'kirundi': 'Icumi na gatanu', 'english': 'Fifteen (15)', 'french': 'Quinze (15)', 'display_order': 15},
        {'category': 'numbers', 'kirundi': 'Icumi na gatandatu', 'english': 'Sixteen (16)', 'french': 'Seize (16)', 'display_order': 16},
        {'category': 'numbers', 'kirundi': 'Icumi n\'indwi', 'english': 'Seventeen (17)', 'french': 'Dix-sept (17)', 'display_order': 17},
        {'category': 'numbers', 'kirundi': 'Icumi n\'umunani', 'english': 'Eighteen (18)', 'french': 'Dix-huit (18)', 'display_order': 18},
        {'category': 'numbers', 'kirundi': 'Icumi n\'icenda', 'english': 'Nineteen (19)', 'french': 'Dix-neuf (19)', 'display_order': 19},
        {'category': 'numbers', 'kirundi': 'Mirongo ibiri', 'english': 'Twenty (20)', 'french': 'Vingt (20)', 'display_order': 20},
        {'category': 'numbers', 'kirundi': 'Mirongo itatu', 'english': 'Thirty (30)', 'french': 'Trente (30)', 'display_order': 21},
        {'category': 'numbers', 'kirundi': 'Mirongo ine', 'english': 'Forty (40)', 'french': 'Quarante (40)', 'display_order': 22},
        {'category': 'numbers', 'kirundi': 'Mirongo itanu', 'english': 'Fifty (50)', 'french': 'Cinquante (50)', 'display_order': 23},
        {'category': 'numbers', 'kirundi': 'Mirongo itandatu', 'english': 'Sixty (60)', 'french': 'Soixante (60)', 'display_order': 24},
        {'category': 'numbers', 'kirundi': 'Mirongo irindwi', 'english': 'Seventy (70)', 'french': 'Soixante-dix (70)', 'display_order': 25},
        {'category': 'numbers', 'kirundi': 'Mirongo inani', 'english': 'Eighty (80)', 'french': 'Quatre-vingts (80)', 'display_order': 26},
        {'category': 'numbers', 'kirundi': 'Mirongo icenda', 'english': 'Ninety (90)', 'french': 'Quatre-vingt-dix (90)', 'display_order': 27},
        {'category': 'numbers', 'kirundi': 'Ijana', 'english': 'One hundred (100)', 'french': 'Cent (100)', 'display_order': 28},
        {'category': 'numbers', 'kirundi': 'Amajana abiri', 'english': 'Two hundred (200)', 'french': 'Deux cents (200)', 'display_order': 29},
        {'category': 'numbers', 'kirundi': 'Amajana atanu', 'english': 'Five hundred (500)', 'french': 'Cinq cents (500)', 'display_order': 30},
        {'category': 'numbers', 'kirundi': 'Igihumbi', 'english': 'One thousand (1,000)', 'french': 'Mille (1 000)', 'display_order': 31},
        {'category': 'numbers', 'kirundi': 'Ibihumbi bitanu', 'english': 'Five thousand (5,000)', 'french': 'Cinq mille (5 000)', 'display_order': 32},
        {'category': 'numbers', 'kirundi': 'Ibihumbi icumi', 'english': 'Ten thousand (10,000)', 'french': 'Dix mille (10 000)', 'display_order': 33},
        {'category': 'numbers', 'kirundi': 'Igice', 'english': 'Half', 'french': 'Demi / Moitié', 'display_order': 34},
        {'category': 'numbers', 'kirundi': 'Ica kabiri', 'english': 'First', 'french': 'Premier', 'display_order': 35},
        {'category': 'numbers', 'kirundi': 'Ica gatatu', 'english': 'Second', 'french': 'Deuxième', 'display_order': 36},
        {'category': 'numbers', 'kirundi': 'Ica kane', 'english': 'Third', 'french': 'Troisième', 'display_order': 37},

        # ════════════════════════════════════════
        # ── FOOD & DRINK ──
        # ════════════════════════════════════════
        {'category': 'food', 'kirundi': 'Amazi', 'english': 'Water', 'french': 'Eau', 'display_order': 1},
        {'category': 'food', 'kirundi': 'Amazi meza', 'english': 'Clean water / Drinking water', 'french': 'Eau potable', 'display_order': 2},
        {'category': 'food', 'kirundi': 'Amazi ashushe', 'english': 'Hot water', 'french': 'Eau chaude', 'display_order': 3},
        {'category': 'food', 'kirundi': 'Amazi akonje', 'english': 'Cold water', 'french': 'Eau froide', 'display_order': 4},
        {'category': 'food', 'kirundi': 'Ikawa', 'english': 'Coffee', 'french': 'Café', 'display_order': 5},
        {'category': 'food', 'kirundi': 'Icayi', 'english': 'Tea', 'french': 'Thé', 'display_order': 6},
        {'category': 'food', 'kirundi': 'Amata', 'english': 'Milk', 'french': 'Lait', 'display_order': 7},
        {'category': 'food', 'kirundi': 'Isukari', 'english': 'Sugar', 'french': 'Sucre', 'display_order': 8},
        {'category': 'food', 'kirundi': 'Umunyu', 'english': 'Salt', 'french': 'Sel', 'display_order': 9},
        {'category': 'food', 'kirundi': 'Umuceri', 'english': 'Rice', 'french': 'Riz', 'display_order': 10},
        {'category': 'food', 'kirundi': 'Inyama', 'english': 'Meat', 'french': 'Viande', 'display_order': 11},
        {'category': 'food', 'kirundi': 'Inyama y\'inka', 'english': 'Beef', 'french': 'Viande de boeuf', 'display_order': 12},
        {'category': 'food', 'kirundi': 'Inyama y\'impene', 'english': 'Goat meat', 'french': 'Viande de chèvre', 'display_order': 13},
        {'category': 'food', 'kirundi': 'Inyama y\'inkoko', 'english': 'Chicken', 'french': 'Poulet', 'display_order': 14},
        {'category': 'food', 'kirundi': 'Ifi', 'english': 'Fish', 'french': 'Poisson', 'display_order': 15},
        {'category': 'food', 'kirundi': 'Amagi', 'english': 'Eggs', 'french': 'Oeufs', 'display_order': 16},
        {'category': 'food', 'kirundi': 'Ibitoki', 'english': 'Bananas', 'french': 'Bananes', 'display_order': 17},
        {'category': 'food', 'kirundi': 'Ibitoki vyo guteka', 'english': 'Cooking bananas / Plantains', 'french': 'Bananes à cuire / Plantains', 'display_order': 18},
        {'category': 'food', 'kirundi': 'Ibijumbu', 'english': 'Sweet potatoes', 'french': 'Patates douces', 'display_order': 19},
        {'category': 'food', 'kirundi': 'Ibiharage', 'english': 'Beans', 'french': 'Haricots', 'display_order': 20},
        {'category': 'food', 'kirundi': 'Ibirayi', 'english': 'Potatoes', 'french': 'Pommes de terre', 'display_order': 21},
        {'category': 'food', 'kirundi': 'Imyumbati', 'english': 'Cassava', 'french': 'Manioc', 'display_order': 22},
        {'category': 'food', 'kirundi': 'Igikoma', 'english': 'Peanuts / Groundnuts', 'french': 'Arachides', 'display_order': 23},
        {'category': 'food', 'kirundi': 'Imboga', 'english': 'Vegetables', 'french': 'Légumes', 'display_order': 24},
        {'category': 'food', 'kirundi': 'Ivyamwa', 'english': 'Fruits', 'french': 'Fruits', 'display_order': 25},
        {'category': 'food', 'kirundi': 'Umwembe', 'english': 'Mango', 'french': 'Mangue', 'display_order': 26},
        {'category': 'food', 'kirundi': 'Inanasi', 'english': 'Pineapple', 'french': 'Ananas', 'display_order': 27},
        {'category': 'food', 'kirundi': 'Ipera', 'english': 'Avocado', 'french': 'Avocat', 'display_order': 28},
        {'category': 'food', 'kirundi': 'Icunga', 'english': 'Orange', 'french': 'Orange', 'display_order': 29},
        {'category': 'food', 'kirundi': 'Umutsima', 'english': 'Cassava paste (staple food)', 'french': 'Pâte de manioc', 'display_order': 30},
        {'category': 'food', 'kirundi': 'Ibinyobwa', 'english': 'Snacks', 'french': 'Collations', 'display_order': 31},
        {'category': 'food', 'kirundi': 'Umuhere', 'english': 'Bread', 'french': 'Pain', 'display_order': 32},
        {'category': 'food', 'kirundi': 'Ndafise inzara', 'english': 'I am hungry', 'french': 'J\'ai faim', 'display_order': 33},
        {'category': 'food', 'kirundi': 'Ndafise inyota', 'english': 'I am thirsty', 'french': 'J\'ai soif', 'display_order': 34},
        {'category': 'food', 'kirundi': 'Ifunguro ry\'igitondo', 'english': 'Breakfast', 'french': 'Petit-déjeuner', 'display_order': 35},
        {'category': 'food', 'kirundi': 'Ifunguro ry\'umutaga', 'english': 'Lunch', 'french': 'Déjeuner', 'display_order': 36},
        {'category': 'food', 'kirundi': 'Ifunguro ry\'ijoro', 'english': 'Dinner', 'french': 'Dîner', 'display_order': 37},
        {'category': 'food', 'kirundi': 'Biryoshe', 'english': 'It is delicious', 'french': 'C\'est délicieux', 'display_order': 38},
        {'category': 'food', 'kirundi': 'Ndashaka ...', 'english': 'I would like ...', 'french': 'Je voudrais ...', 'display_order': 39},
        {'category': 'food', 'kirundi': 'Nshaka ikawa idafise isukari', 'english': 'I want coffee without sugar', 'french': 'Je veux du café sans sucre', 'display_order': 40},
        {'category': 'food', 'kirundi': 'Bimaze', 'english': 'I am full / That is enough', 'french': 'Je suis rassasié(e) / Ça suffit', 'display_order': 41},
        {'category': 'food', 'kirundi': 'Inzoga', 'english': 'Beer / Alcohol', 'french': 'Bière / Alcool', 'display_order': 42},
        {'category': 'food', 'kirundi': 'Urwarwa', 'english': 'Banana beer (traditional)', 'french': 'Bière de banane (traditionnelle)', 'display_order': 43},
        {'category': 'food', 'kirundi': 'Impeke', 'english': 'Sorghum beer (traditional)', 'french': 'Bière de sorgho (traditionnelle)', 'display_order': 44},
        {'category': 'food', 'kirundi': 'Ikirahure', 'english': 'Yoghurt', 'french': 'Yaourt', 'display_order': 45},

        # ════════════════════════════════════════
        # ── TRAVEL & TRANSPORT ──
        # ════════════════════════════════════════
        {'category': 'travel', 'kirundi': 'Ikibuga c\'indege', 'english': 'Airport', 'french': 'Aéroport', 'display_order': 1},
        {'category': 'travel', 'kirundi': 'Ihoteli', 'english': 'Hotel', 'french': 'Hôtel', 'display_order': 2},
        {'category': 'travel', 'kirundi': 'Ipasiporo', 'english': 'Passport', 'french': 'Passeport', 'display_order': 3},
        {'category': 'travel', 'kirundi': 'Iviza', 'english': 'Visa', 'french': 'Visa', 'display_order': 4},
        {'category': 'travel', 'kirundi': 'Ikaze mu Burundi', 'english': 'Welcome to Burundi', 'french': 'Bienvenue au Burundi', 'display_order': 5},
        {'category': 'travel', 'kirundi': 'Imodoka', 'english': 'Car', 'french': 'Voiture', 'display_order': 6},
        {'category': 'travel', 'kirundi': 'Ibisi', 'english': 'Bus', 'french': 'Bus', 'display_order': 7},
        {'category': 'travel', 'kirundi': 'Indege', 'english': 'Airplane', 'french': 'Avion', 'display_order': 8},
        {'category': 'travel', 'kirundi': 'Ubwato', 'english': 'Boat', 'french': 'Bateau', 'display_order': 9},
        {'category': 'travel', 'kirundi': 'Igare', 'english': 'Station', 'french': 'Gare', 'display_order': 10},
        {'category': 'travel', 'kirundi': 'Ibarabara', 'english': 'Road', 'french': 'Route', 'display_order': 11},
        {'category': 'travel', 'kirundi': 'Igitikisi', 'english': 'Taxi', 'french': 'Taxi', 'display_order': 12},
        {'category': 'travel', 'kirundi': 'Ndashaka igitikisi', 'english': 'I need a taxi', 'french': 'J\'ai besoin d\'un taxi', 'display_order': 13},
        {'category': 'travel', 'kirundi': 'Ipikipiki', 'english': 'Motorcycle / Motorbike', 'french': 'Moto', 'display_order': 14},
        {'category': 'travel', 'kirundi': 'Igipimo', 'english': 'Ticket', 'french': 'Billet', 'display_order': 15},
        {'category': 'travel', 'kirundi': 'Umupaka', 'english': 'Border', 'french': 'Frontière', 'display_order': 16},
        {'category': 'travel', 'kirundi': 'Uburyo bwo kwinjira', 'english': 'Entrance', 'french': 'Entrée', 'display_order': 17},
        {'category': 'travel', 'kirundi': 'Uburyo bwo gusohoka', 'english': 'Exit', 'french': 'Sortie', 'display_order': 18},
        {'category': 'travel', 'kirundi': 'Bujumbura', 'english': 'Bujumbura (economic capital)', 'french': 'Bujumbura (capitale économique)', 'display_order': 19},
        {'category': 'travel', 'kirundi': 'Gitega', 'english': 'Gitega (political capital)', 'french': 'Gitega (capitale politique)', 'display_order': 20},
        {'category': 'travel', 'kirundi': 'Ikiyaga Tanganyika', 'english': 'Lake Tanganyika', 'french': 'Lac Tanganyika', 'display_order': 21},
        {'category': 'travel', 'kirundi': 'Inzuzi', 'english': 'River', 'french': 'Rivière', 'display_order': 22},
        {'category': 'travel', 'kirundi': 'Umusozi', 'english': 'Mountain / Hill', 'french': 'Montagne / Colline', 'display_order': 23},
        {'category': 'travel', 'kirundi': 'Ishamba', 'english': 'Forest', 'french': 'Forêt', 'display_order': 24},
        {'category': 'travel', 'kirundi': 'Ikibira', 'english': 'National park / Forest reserve', 'french': 'Parc national / Réserve forestière', 'display_order': 25},
        {'category': 'travel', 'kirundi': 'Ndashaka icumba', 'english': 'I want a room', 'french': 'Je veux une chambre', 'display_order': 26},
        {'category': 'travel', 'kirundi': 'Icumba c\'umuntu umwe', 'english': 'Single room', 'french': 'Chambre simple', 'display_order': 27},
        {'category': 'travel', 'kirundi': 'Icumba c\'abantu babiri', 'english': 'Double room', 'french': 'Chambre double', 'display_order': 28},
        {'category': 'travel', 'kirundi': 'Ni angahe ku joro?', 'english': 'How much per night?', 'french': 'Combien par nuit ?', 'display_order': 29},
        {'category': 'travel', 'kirundi': 'Nshaka gufata indege', 'english': 'I want to catch a flight', 'french': 'Je veux prendre un vol', 'display_order': 30},
        {'category': 'travel', 'kirundi': 'Indege igenda ryari?', 'english': 'When does the plane leave?', 'french': 'Quand part l\'avion ?', 'display_order': 31},
        {'category': 'travel', 'kirundi': 'Umuzigo', 'english': 'Luggage / Baggage', 'french': 'Bagages', 'display_order': 32},
        {'category': 'travel', 'kirundi': 'Ndashaka guhindura amafaranga', 'english': 'I want to exchange money', 'french': 'Je veux changer de l\'argent', 'display_order': 33},
        {'category': 'travel', 'kirundi': 'Wi-Fi iri hehe?', 'english': 'Where is the Wi-Fi?', 'french': 'Où est le Wi-Fi ?', 'display_order': 34},
        {'category': 'travel', 'kirundi': 'Ijambo ry\'ibanga rya Wi-Fi ni irihe?', 'english': 'What is the Wi-Fi password?', 'french': 'Quel est le mot de passe Wi-Fi ?', 'display_order': 35},

        # ════════════════════════════════════════
        # ── CULTURE & TRADITIONS ──
        # ════════════════════════════════════════
        {'category': 'culture', 'kirundi': 'Ingoma', 'english': 'Drum / Royal drums', 'french': 'Tambour / Tambours royaux', 'display_order': 1},
        {'category': 'culture', 'kirundi': 'Ingoma z\'i Burundi', 'english': 'Sacred drums of Burundi (UNESCO heritage)', 'french': 'Tambours sacrés du Burundi (patrimoine UNESCO)', 'display_order': 2},
        {'category': 'culture', 'kirundi': 'Intore', 'english': 'Traditional warrior dance', 'french': 'Danse traditionnelle des guerriers', 'display_order': 3},
        {'category': 'culture', 'kirundi': 'Ubuntu', 'english': 'Humanity / Compassion / Togetherness', 'french': 'Humanité / Compassion / Solidarité', 'display_order': 4},
        {'category': 'culture', 'kirundi': 'Umuganda', 'english': 'Community work', 'french': 'Travail communautaire', 'display_order': 5},
        {'category': 'culture', 'kirundi': 'Umuganuro', 'english': 'Harvest festival / Sorghum festival', 'french': 'Fête des récoltes / Fête du sorgho', 'display_order': 6},
        {'category': 'culture', 'kirundi': 'Ikamba', 'english': 'Crown', 'french': 'Couronne', 'display_order': 7},
        {'category': 'culture', 'kirundi': 'Umwami', 'english': 'King', 'french': 'Roi', 'display_order': 8},
        {'category': 'culture', 'kirundi': 'Umwamikazi', 'english': 'Queen', 'french': 'Reine', 'display_order': 9},
        {'category': 'culture', 'kirundi': 'Inka', 'english': 'Cow (symbol of wealth and status)', 'french': 'Vache (symbole de richesse et de statut)', 'display_order': 10},
        {'category': 'culture', 'kirundi': 'Agaseke', 'english': 'Traditional woven basket', 'french': 'Panier tressé traditionnel', 'display_order': 11},
        {'category': 'culture', 'kirundi': 'Ikigabiro', 'english': 'Royal stool / Throne', 'french': 'Tabouret royal / Trône', 'display_order': 12},
        {'category': 'culture', 'kirundi': 'Imvyino', 'english': 'Song / Music', 'french': 'Chanson / Musique', 'display_order': 13},
        {'category': 'culture', 'kirundi': 'Umuziki', 'english': 'Music', 'french': 'Musique', 'display_order': 14},
        {'category': 'culture', 'kirundi': 'Igisoro', 'english': 'Traditional board game (mancala)', 'french': 'Jeu de plateau traditionnel (mancala)', 'display_order': 15},
        {'category': 'culture', 'kirundi': 'Umuco', 'english': 'Culture / Tradition', 'french': 'Culture / Tradition', 'display_order': 16},
        {'category': 'culture', 'kirundi': 'Ikirundi', 'english': 'Kirundi language', 'french': 'Langue kirundi', 'display_order': 17},
        {'category': 'culture', 'kirundi': 'Imigani', 'english': 'Proverbs / Riddles', 'french': 'Proverbes / Devinettes', 'display_order': 18},
        {'category': 'culture', 'kirundi': 'Igitaramo', 'english': 'Celebration / Festival', 'french': 'Célébration / Fête', 'display_order': 19},
        {'category': 'culture', 'kirundi': 'Ubukwe', 'english': 'Wedding', 'french': 'Mariage', 'display_order': 20},
        {'category': 'culture', 'kirundi': 'Gusaba', 'english': 'Traditional marriage proposal', 'french': 'Demande en mariage traditionnelle', 'display_order': 21},
        {'category': 'culture', 'kirundi': 'Gukwa', 'english': 'Bride price / Dowry ceremony', 'french': 'Dot / Cérémonie de la dot', 'display_order': 22},
        {'category': 'culture', 'kirundi': 'Inkuru y\'Uburundi', 'english': 'History of Burundi', 'french': 'Histoire du Burundi', 'display_order': 23},
        {'category': 'culture', 'kirundi': 'Ibendera ry\'Uburundi', 'english': 'Flag of Burundi', 'french': 'Drapeau du Burundi', 'display_order': 24},
        {'category': 'culture', 'kirundi': 'Indirimbo y\'igihugu', 'english': 'National anthem', 'french': 'Hymne national', 'display_order': 25},
        {'category': 'culture', 'kirundi': 'Urwarwa', 'english': 'Banana wine (cultural drink)', 'french': 'Vin de banane (boisson culturelle)', 'display_order': 26},
        {'category': 'culture', 'kirundi': 'Igiti c\'amahoro', 'english': 'Tree of peace', 'french': 'Arbre de la paix', 'display_order': 27},
        {'category': 'culture', 'kirundi': 'Ishaka', 'english': 'Forest / Sacred grove', 'french': 'Forêt / Bois sacré', 'display_order': 28},
        {'category': 'culture', 'kirundi': 'Abatimbo', 'english': 'Drummers', 'french': 'Tambourinaires', 'display_order': 29},
        {'category': 'culture', 'kirundi': 'Umurishyo', 'english': 'Traditional dance performance', 'french': 'Spectacle de danse traditionnelle', 'display_order': 30},

        # ════════════════════════════════════════
        # ── BUSINESS & COMMERCE ──
        # ════════════════════════════════════════
        {'category': 'business', 'kirundi': 'Amafaranga', 'english': 'Money', 'french': 'Argent', 'display_order': 1},
        {'category': 'business', 'kirundi': 'Amafaranga y\'Uburundi', 'english': 'Burundian Franc (BIF)', 'french': 'Franc burundais (BIF)', 'display_order': 2},
        {'category': 'business', 'kirundi': 'Idolari', 'english': 'Dollar', 'french': 'Dollar', 'display_order': 3},
        {'category': 'business', 'kirundi': 'Igiciro ni kingana?', 'english': 'How much does it cost?', 'french': 'Combien ça coûte ?', 'display_order': 4},
        {'category': 'business', 'kirundi': 'Ni birengeye', 'english': 'It is too expensive', 'french': 'C\'est trop cher', 'display_order': 5},
        {'category': 'business', 'kirundi': 'Gabanya igiciro', 'english': 'Reduce the price', 'french': 'Réduisez le prix', 'display_order': 6},
        {'category': 'business', 'kirundi': 'Isoko', 'english': 'Market', 'french': 'Marché', 'display_order': 7},
        {'category': 'business', 'kirundi': 'Ibanki', 'english': 'Bank', 'french': 'Banque', 'display_order': 8},
        {'category': 'business', 'kirundi': 'Iduka', 'english': 'Shop / Store', 'french': 'Magasin / Boutique', 'display_order': 9},
        {'category': 'business', 'kirundi': 'Ndashaka kugura ...', 'english': 'I want to buy ...', 'french': 'Je veux acheter ...', 'display_order': 10},
        {'category': 'business', 'kirundi': 'Ndashaka kugurisha ...', 'english': 'I want to sell ...', 'french': 'Je veux vendre ...', 'display_order': 11},
        {'category': 'business', 'kirundi': 'Akazi', 'english': 'Work / Job', 'french': 'Travail / Emploi', 'display_order': 12},
        {'category': 'business', 'kirundi': 'Umushahara', 'english': 'Salary', 'french': 'Salaire', 'display_order': 13},
        {'category': 'business', 'kirundi': 'Ikigo', 'english': 'Organization / Institution', 'french': 'Organisation / Institution', 'display_order': 14},
        {'category': 'business', 'kirundi': 'Ibiro', 'english': 'Office', 'french': 'Bureau', 'display_order': 15},
        {'category': 'business', 'kirundi': 'Inama y\'akazi', 'english': 'Business meeting', 'french': 'Réunion de travail', 'display_order': 16},
        {'category': 'business', 'kirundi': 'Kwishura', 'english': 'To pay', 'french': 'Payer', 'display_order': 17},
        {'category': 'business', 'kirundi': 'Ndashaka kwishura', 'english': 'I want to pay', 'french': 'Je veux payer', 'display_order': 18},
        {'category': 'business', 'kirundi': 'Mwemera amadolari?', 'english': 'Do you accept dollars?', 'french': 'Acceptez-vous les dollars ?', 'display_order': 19},
        {'category': 'business', 'kirundi': 'Mwemera ikarata?', 'english': 'Do you accept cards?', 'french': 'Acceptez-vous les cartes ?', 'display_order': 20},
        {'category': 'business', 'kirundi': 'Nimba mfise ikibazo', 'english': 'If I have a problem', 'french': 'Si j\'ai un problème', 'display_order': 21},
        {'category': 'business', 'kirundi': 'Fagitire', 'english': 'Receipt / Invoice', 'french': 'Reçu / Facture', 'display_order': 22},
        {'category': 'business', 'kirundi': 'Ndashaka fagitire', 'english': 'I need a receipt', 'french': 'J\'ai besoin d\'un reçu', 'display_order': 23},
        {'category': 'business', 'kirundi': 'Umudandaza', 'english': 'Merchant / Trader', 'french': 'Commerçant', 'display_order': 24},
        {'category': 'business', 'kirundi': 'Ubudandaji', 'english': 'Commerce / Trade', 'french': 'Commerce', 'display_order': 25},
        {'category': 'business', 'kirundi': 'Igiciro kibereye', 'english': 'Fair price', 'french': 'Prix juste', 'display_order': 26},
        {'category': 'business', 'kirundi': 'Ubucuruzi', 'english': 'Business / Enterprise', 'french': 'Affaires / Entreprise', 'display_order': 27},
        {'category': 'business', 'kirundi': 'Mobile Money', 'english': 'Mobile Money (Lumicash / Ecocash)', 'french': 'Mobile Money (Lumicash / Ecocash)', 'display_order': 28},
        {'category': 'business', 'kirundi': 'Ndashaka kohereza amafaranga', 'english': 'I want to send money', 'french': 'Je veux envoyer de l\'argent', 'display_order': 29},
        {'category': 'business', 'kirundi': 'Ndashaka gukura amafaranga', 'english': 'I want to withdraw money', 'french': 'Je veux retirer de l\'argent', 'display_order': 30},
    ]

    PhrasebookEntry.objects.bulk_create([
        PhrasebookEntry(**entry) for entry in entries
    ])


def reverse_seed(apps, schema_editor):
    PhrasebookEntry = apps.get_model('core', 'PhrasebookEntry')
    PhrasebookEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_add_event_map_url'),
    ]

    operations = [
        migrations.RunPython(seed_phrasebook, reverse_seed),
    ]
