# Generated by Django 5.2.16 on 2026-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_fix_yd_document_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdialogueevent',
            name='auto_approve_documents',
            field=models.BooleanField(default=False, help_text='Auto-validate and approve uploaded documents. Photos require face detection.'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='sos_title',
            field=models.CharField(blank=True, default='SOS Burundi', help_text='SOS screen title (English)', max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='sos_title_fr',
            field=models.CharField(blank=True, default='SOS Burundi', help_text='SOS screen title (French)', max_length=100),
        ),
    ]
