# Generated by Django 4.2.28 on 2026-09-01 12:21

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0165_auto_approve_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "African Union"', max_length=100)),
                ('kind', models.CharField(choices=[('x', 'X / Twitter account'), ('rss', 'RSS / Atom feed')], default='rss', max_length=10)),
                ('target', models.CharField(help_text='X handle without the @ (e.g. BurundinAddis), or the full feed URL', max_length=500)),
                ('attribution', models.CharField(blank=True, help_text='Credit shown on reposts, e.g. "via African Union". Leave blank for our own posts.', max_length=100)),
                ('is_own_content', models.BooleanField(default=False, help_text='On = our own posts (no credit line). Off = a repost, credited to this source.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_category', models.ForeignKey(blank=True, help_text='Category applied to articles approved from this source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_sources', to='core.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Tweet id or feed entry guid — used to avoid re-importing the same post', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='scraped/', validators=[core.validators.validate_image_file])),
                ('image_url', models.URLField(blank=True, help_text='Original image URL at the source', max_length=1000)),
                ('source_url', models.URLField(blank=True, help_text='Permalink back to the original post', max_length=1000)),
                ('published_at', models.DateTimeField(db_index=True, help_text='When the source published it')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Original metadata from the source')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, help_text='The article created when this item was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_from', to='core.article')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scraped_items', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='core_scrape_status_40b28c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scrapeditem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_scraped_item_per_source'),
        ),
    ]
