# Generated by Django 5.2.16 on 2026-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_newssource_scrapeditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('arise', 'A-RISE Youth Voices'), ('events', 'Events'), ('culture', 'Culture'), ('politics', 'Politics & Diplomacy'), ('business', 'Business & Trade'), ('announcements', 'Announcements')], default='general', max_length=20),
        ),
    ]
