# Generated by Django 5.2.16 on 2026-09-02 11:25

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_alter_discussion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='discussion_media/', validators=[core.validators.validate_image_file])),
                ('video', models.FileField(blank=True, upload_to='discussion_media/', validators=[core.validators.validate_video_file])),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.discussion')),
            ],
            options={
                'verbose_name': 'Discussion Media',
                'verbose_name_plural': 'Discussion Media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
