# Generated by Django 5.2.16 on 2026-09-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_discussion_repost_of_alter_discussion_title_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or hate'), ('violence', 'Violence or threats'), ('sexual', 'Sexual content'), ('misinformation', 'False information'), ('other', 'Something else')], default='other', max_length=20)),
                ('detail', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.discussion')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Report',
                'verbose_name_plural': 'Content Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_conten_status_90e95e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('discussion__isnull', False)), fields=('reporter', 'discussion'), name='unique_report_per_discussion'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False)), fields=('reporter', 'reported_user'), name='unique_report_per_user')],
            },
        ),
    ]
