# Generated by Django 5.2.16 on 2026-09-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_contentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('title_fr', models.CharField(blank=True, max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('description_fr', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('general', 'General'), ('arise', 'A-RISE Youth Voices'), ('events', 'Events'), ('culture', 'Culture'), ('politics', 'Politics & Diplomacy'), ('business', 'Business & Trade'), ('announcements', 'Announcements')], default='general', help_text='Category applied to posts started from this topic.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discussion Topic',
                'verbose_name_plural': 'Discussion Topics',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='discussion',
            field=models.OneToOneField(blank=True, help_text='Set when this poll was attached to a feed post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='core.discussion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The admin-authored prompt this post answers, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.discussiontopic'),
        ),
    ]
