# Generated by Django 5.2.16 on 2026-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_discussiontopic_poll_discussion_discussion_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='explore_terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the Explore community terms. Null = not yet.', null=True),
        ),
    ]
