# Generated by Django 5.2.16 on 2026-09-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_userprofile_explore_terms_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('follow', 'Started following you'), ('like', 'Liked your post'), ('reply', 'Replied to your post'), ('repost', 'Reposted your post')], max_length=12)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_actions', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.discussion')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explore Notification',
                'verbose_name_plural': 'Explore Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_explor_recipie_94f2ee_idx'), models.Index(fields=['recipient', 'is_read'], name='core_explor_recipie_a5d4a6_idx')],
            },
        ),
    ]
