# Generated by Django 5.2.16 on 2026-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_explorenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_enabled',
            field=models.BooleanField(default=True, help_text='Show the "New today" rail at the top of the home screen'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_event_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Upcoming events in the "New today" rail (0 = hide)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_feature_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Feature cards in the "New today" rail (0 = hide)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_live_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Live feeds in the "New today" rail (0 = hide)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_magazine_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Magazines in the "New today" rail (0 = hide)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_news_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='News/articles in the "New today" rail (0 = hide)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hero_rail_video_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Videos in the "New today" rail (0 = hide)'),
        ),
    ]
