# Generated by Django 5.2.16 on 2026-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_appsettings_hero_rail_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, help_text='Short self-description shown on the Explore profile.', max_length=200),
        ),
    ]
