# Generated by Django 5.2.17 on 2026-09-03 08:42

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_official_posting_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='refresh_jti',
            field=models.CharField(blank=True, db_index=True, help_text='jti of the refresh token issued for this session', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, storage=core.models._private_storage, upload_to='messages/attachments/', validators=[core.validators.validate_image_file]),
        ),
    ]
