# Generated by Django 5.2.17 on 2026-09-03 09:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class PostgresOnlyAddIndex(migrations.AddIndex):
    """GIN indexes only exist on Postgres; SQLite (dev/test) keeps the state change only."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)


def dedupe_self_registrations(apps, schema_editor):
    """Keep the earliest self-registration per (user, event); the view already
    refused later ones, so any extras are race-condition duplicates."""
    EventSubmission = apps.get_model('core', 'EventSubmission')
    seen = set()
    for sub in EventSubmission.objects.filter(is_proxy=False).order_by('submitted_at', 'id').only('id', 'user_id', 'event_registration_id'):
        key = (sub.user_id, sub.event_registration_id)
        if key in seen:
            sub.delete()
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_activesession_refresh_jti_directmessage_private_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['order', '-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='magazineedition',
            options={'ordering': ['-publish_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-is_featured', '-publish_date', '-id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='newsletteredition',
            name='sent_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Chunk indexes already delivered (retry guard)'),
        ),
        PostgresOnlyAddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'title_fr', 'content', 'content_fr', config='simple'), name='article_search_gin'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='core_discus_is_pinn_fd9f26_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', 'created_at'], name='core_userse_ip_addr_27b431_idx'),
        ),
        migrations.RunPython(dedupe_self_registrations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_proxy', False)), fields=('user', 'event_registration'), name='uniq_self_registration_per_event'),
        ),
    ]
