# Generated by Django 5.2.17 on 2026-09-03 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_correctness_perf_indexes_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Set the first time the author edits the text.', null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the feed pending moderator review.'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_against', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='core_block_blocker_96d5d6_idx'), models.Index(fields=['blocked'], name='core_block_blocked_0807ff_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='DiscussionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.discussion')),
            ],
            options={
                'indexes': [models.Index(fields=['tag', '-discussion'], name='core_discus_tag_e02a38_idx')],
                'unique_together': {('discussion', 'tag')},
            },
        ),
    ]
