# Generated by Django 5.2.17 on 2026-09-04 15:04

from django.db import migrations, models

OLD = 'info@burundi4africa.com'
NEW = 'info@burundichairship.africa'


def move_contact_email(apps, schema_editor):
    """Changing the field default only affects new rows; the live settings row
    already exists, so carry it over too — unless someone has set their own."""
    AppSettings = apps.get_model('core', 'AppSettings')
    AppSettings.objects.filter(contact_email=OLD).update(contact_email=NEW)


def restore_contact_email(apps, schema_editor):
    AppSettings = apps.get_model('core', 'AppSettings')
    AppSettings.objects.filter(contact_email=NEW).update(contact_email=OLD)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@burundichairship.africa', help_text='Contact email address', max_length=254),
        ),
        migrations.RunPython(move_contact_email, restore_contact_email),
    ]
