# Generated by Django 5.2.16 on 2026-09-08 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_contact_email_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='auto_fetch',
            field=models.BooleanField(default=False, help_text='On = fetch this source once a day automatically, into the same review queue.'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='auto_fetch_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='How far back each daily fetch looks, in days. 2 covers a missed run.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='newssource',
            name='auto_fetch_hour',
            field=models.PositiveSmallIntegerField(default=6, help_text='Hour of the day (0-23, server local time) the daily fetch runs.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
