# Generated by Django 5.2.16 on 2026-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_newssource_auto_fetch_newssource_auto_fetch_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='x_cookies',
            field=models.TextField(blank=True, help_text='Netscape cookies.txt contents for X. Use a throwaway X account: this is a live session, not a scoped API key.'),
        ),
    ]
