# Generated by Django 5.2.16 on 2026-09-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_appsettings_x_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemedia',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
