# Generated by Django 5.2.16 on 2026-09-09 22:50

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the news scraper.

    Reading X programmatically stopped being viable: gallery-dl's date-bounded
    search loops on X's rate limits (mikf/gallery-dl#9524, #7766), and a
    session cookie expires within days. Approved articles are ordinary
    Articles and are untouched — only the candidate queue and its sources go.
    """


    dependencies = [
        ('core', '0186_merge_cache_table_branches'),
    ]

    operations = [
        # Dropping each FK before the table it belongs to is both redundant and
        # something SQLite's table rebuild cannot do; the tables go whole.
        migrations.DeleteModel(name='ScrapedItem'),
        migrations.DeleteModel(name='NewsSource'),
        migrations.RemoveField(model_name='appsettings', name='x_cookies'),
    ]
