# Generated by Django 5.2.16 on 2026-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_remove_news_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID, if the platform shows one', max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_passcode',
            field=models.CharField(blank=True, help_text='Meeting passcode, if there is one', max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Google Meet / Zoom / Teams link, for Online and Hybrid events', max_length=500),
        ),
    ]
